/**
 * assembleWorkspaceBundle — top-level orchestrator for a per-creator
 * OpenClaw workspace.
 *
 * Sprint 3.7 phase A. Calls the 7 file generators + the cron jobs.json
 * builder, returns a `Map<filename, content>` the deploy pipeline
 * serializes for upload to the Fly machine's persistent volume.
 *
 * Files emitted (per OpenClaw spec
 * `https://docs.openclaw.ai/concepts/agent-workspace.md`):
 *
 *   - `AGENTS.md`                                     — always
 *   - `USER.md`                                       — always
 *   - `HEARTBEAT.md`                                  — always
 *   - `BOOT.md`                                       — always
 *   - `MEMORY.md`                                     — always (initial seed)
 *   - `TOOLS.md`                                      — always
 *   - `DREAMING.md`                                   — always
 *   - `standing-orders.md`                            — only if AGENTS.md
 *                                                       embedded form
 *                                                       exceeds bootstrapMaxChars
 *   - `Operations/Daily Notes/README.md`              — always (seed)
 *   - `Operations/Daily Notes/<today-local>.md`       — always (seed)
 *
 * SOUL.md is generated by the separate Sprint 2 `generateSoul()` task. Our
 * bundle assumes that function exists and emits SOUL.md alongside.
 *
 * Pure function. Deterministic for given inputs (with `now` pinned).
 */

import {
  generateAgentsMd,
  renderStandingOrdersDocument,
  DEFAULT_BOOTSTRAP_MAX_CHARS,
} from "./generateAgentsMd";
import { generateUserMd, deriveDisplayName } from "./generateUserMd";
import { generateHeartbeatMd } from "./generateHeartbeatMd";
import { generateBootMd } from "./generateBootMd";
import { generateMemoryMdSeed } from "./generateMemoryMdSeed";
import { generateToolsMd } from "./generateToolsMd";
import { generateDreamingMd } from "./generateDreamingMd";
import { buildCronJobsJson, type JobsJson } from "./buildCronJobsJson";
import type { WorkspaceInputs } from "./types";

export interface WorkspaceBundle {
  files: Map<string, string>;
  jobsJson: JobsJson;
  /** Whether AGENTS.md split standing orders into a separate file. */
  standingOrdersSplit: boolean;
}

export interface AssembleBundleOptions {
  /** OpenClaw bootstrap cap; defaults to 12,000. */
  bootstrapMaxChars?: number;
}

export function assembleWorkspaceBundle(
  inputs: WorkspaceInputs,
  options: AssembleBundleOptions = {}
): WorkspaceBundle {
  const { creator, picture, handles, plan, now } = inputs;
  const bootstrapMaxChars = options.bootstrapMaxChars ?? DEFAULT_BOOTSTRAP_MAX_CHARS;
  const displayName = deriveDisplayName(creator.email);

  const sortedHandlesForHeader = [...handles]
    .sort((a, b) => {
      if (a.platform !== b.platform) return a.platform.localeCompare(b.platform);
      return a.handle.localeCompare(b.handle);
    })
    .map((h) => ({ platform: h.platform, handle: h.handle }));

  // First, try the embedded form. If it overflows, fall back to split.
  const embedded = generateAgentsMd({
    creatorDisplayName: displayName,
    plan,
    handles: sortedHandlesForHeader,
    embedStandingOrders: true,
    bootstrapMaxChars,
  });
  let agentsMd: string;
  let standingOrdersSplit = false;
  if (embedded.length <= bootstrapMaxChars) {
    agentsMd = embedded;
  } else {
    agentsMd = generateAgentsMd({
      creatorDisplayName: displayName,
      plan,
      handles: sortedHandlesForHeader,
      embedStandingOrders: false,
      bootstrapMaxChars,
    });
    standingOrdersSplit = true;
  }

  const userMd = generateUserMd({ creator, picture, handles, plan });
  const heartbeatMd = generateHeartbeatMd({ plan });
  const bootMd = generateBootMd({ creatorDisplayName: displayName });
  const memoryMd = generateMemoryMdSeed({ creator, picture, handles, now });
  const toolsMd = generateToolsMd();
  const dreamingMd = generateDreamingMd();

  const files = new Map<string, string>();
  files.set("AGENTS.md", agentsMd);
  files.set("USER.md", userMd);
  files.set("HEARTBEAT.md", heartbeatMd);
  files.set("BOOT.md", bootMd);
  files.set("MEMORY.md", memoryMd);
  files.set("TOOLS.md", toolsMd);
  files.set("DREAMING.md", dreamingMd);
  if (standingOrdersSplit) {
    files.set("standing-orders.md", renderStandingOrdersDocument(plan));
  }

  // Operations / Daily Notes seed — README + today's empty note.
  const todayLocal = formatLocalDate(now, creator.timezone);
  files.set(
    "Operations/Daily Notes/README.md",
    [
      "# Daily Notes",
      "",
      "Append-only log Maya reads and writes during the day. Each file is one local-day. Maya appends notes after every cron tick that produced a creator-facing output (morning brief, evening recap, weekly review, post-publish reaction, brand-email triage, contract scan).",
      "",
      "Format conventions:",
      "",
      "- Filenames: `YYYY-MM-DD.md` in the creator's local timezone (`creators.timezone`).",
      "- Each entry: `## HH:MM <program>` heading, then a short note (one paragraph) about what fired and any open thread.",
      "- Old files are not garbage-collected — they're the audit trail.",
      "",
    ].join("\n")
  );
  files.set(
    `Operations/Daily Notes/${todayLocal}.md`,
    [
      `# ${todayLocal}`,
      "",
      "_(empty — Maya appends after the first cron tick today.)_",
      "",
    ].join("\n")
  );

  const jobsJson = buildCronJobsJson({ creator });

  return { files, jobsJson, standingOrdersSplit };
}

/**
 * Format a unix-ms timestamp as `YYYY-MM-DD` in the given IANA timezone.
 *
 * We use Intl.DateTimeFormat with `en-CA` locale, which natively renders
 * ISO-style dates (YYYY-MM-DD) — the simplest deterministic way to get
 * the local date without pulling in a tz library.
 */
function formatLocalDate(unixMs: number, tz: string): string {
  const fmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  return fmt.format(new Date(unixMs));
}
