/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _admin_realWorldDeployGtm from "../_admin/realWorldDeployGtm.js";
import type * as _admin_zernioLiveSmoke from "../_admin/zernioLiveSmoke.js";
import type * as accountDeletion from "../accountDeletion.js";
import type * as admin from "../admin.js";
import type * as agents_modelRouter_logCall from "../agents/modelRouter/logCall.js";
import type * as agents_modelRouter_maya from "../agents/modelRouter/maya.js";
import type * as agents_modelRouter_openRouterClient from "../agents/modelRouter/openRouterClient.js";
import type * as agents_modelRouter_taskTags from "../agents/modelRouter/taskTags.js";
import type * as agents_packs_maya_bundledPlugin from "../agents/packs/maya/bundledPlugin.js";
import type * as agents_packs_maya_bundledSkills from "../agents/packs/maya/bundledSkills.js";
import type * as agents_packs_maya_generators from "../agents/packs/maya/generators.js";
import type * as agents_packs_maya_gtm_bundledGtmPlugin from "../agents/packs/maya_gtm/bundledGtmPlugin.js";
import type * as agents_packs_maya_gtm_bundledLocalSkills from "../agents/packs/maya_gtm/bundledLocalSkills.js";
import type * as agents_packs_maya_gtm_bundledPlaybook from "../agents/packs/maya_gtm/bundledPlaybook.js";
import type * as agents_packs_maya_gtm_generators from "../agents/packs/maya_gtm/generators.js";
import type * as agents_packs_maya_gtm_pinnedClawhubSkills from "../agents/packs/maya_gtm/pinnedClawhubSkills.js";
import type * as billing_checkout from "../billing/checkout.js";
import type * as billing_gtmBilling from "../billing/gtmBilling.js";
import type * as billing_portal from "../billing/portal.js";
import type * as billing_priceIds from "../billing/priceIds.js";
import type * as billing_stripeClient from "../billing/stripeClient.js";
import type * as billing_stripeWebhookHttp from "../billing/stripeWebhookHttp.js";
import type * as billing_webhook from "../billing/webhook.js";
import type * as creators from "../creators.js";
import type * as crons from "../crons.js";
import type * as founder_dashboard from "../founder/dashboard.js";
import type * as founder_fleetHealth from "../founder/fleetHealth.js";
import type * as gtmMaya_accountLifecycle from "../gtmMaya/accountLifecycle.js";
import type * as gtmMaya_agentLifecycle from "../gtmMaya/agentLifecycle.js";
import type * as gtmMaya_appInspector from "../gtmMaya/appInspector.js";
import type * as gtmMaya_approvalPublishing from "../gtmMaya/approvalPublishing.js";
import type * as gtmMaya_archetypeBrain from "../gtmMaya/archetypeBrain.js";
import type * as gtmMaya_attribution from "../gtmMaya/attribution.js";
import type * as gtmMaya_autonomyPolicy from "../gtmMaya/autonomyPolicy.js";
import type * as gtmMaya_betaGuards from "../gtmMaya/betaGuards.js";
import type * as gtmMaya_calendarOAuth from "../gtmMaya/calendarOAuth.js";
import type * as gtmMaya_calendarPlan from "../gtmMaya/calendarPlan.js";
import type * as gtmMaya_calendarWrite from "../gtmMaya/calendarWrite.js";
import type * as gtmMaya_channelAgents from "../gtmMaya/channelAgents.js";
import type * as gtmMaya_channelScoring from "../gtmMaya/channelScoring.js";
import type * as gtmMaya_channelSelection from "../gtmMaya/channelSelection.js";
import type * as gtmMaya_channelWarmth from "../gtmMaya/channelWarmth.js";
import type * as gtmMaya_contentQuality from "../gtmMaya/contentQuality.js";
import type * as gtmMaya_contentReview from "../gtmMaya/contentReview.js";
import type * as gtmMaya_conversionPing from "../gtmMaya/conversionPing.js";
import type * as gtmMaya_costCap from "../gtmMaya/costCap.js";
import type * as gtmMaya_costLedger from "../gtmMaya/costLedger.js";
import type * as gtmMaya_creatifyVideo from "../gtmMaya/creatifyVideo.js";
import type * as gtmMaya_creativeBudgetGate from "../gtmMaya/creativeBudgetGate.js";
import type * as gtmMaya_deepLink from "../gtmMaya/deepLink.js";
import type * as gtmMaya_deliveryFailures from "../gtmMaya/deliveryFailures.js";
import type * as gtmMaya_demandIntel from "../gtmMaya/demandIntel.js";
import type * as gtmMaya_discoveryBudgetGate from "../gtmMaya/discoveryBudgetGate.js";
import type * as gtmMaya_distributionMotions from "../gtmMaya/distributionMotions.js";
import type * as gtmMaya_engagementLedger from "../gtmMaya/engagementLedger.js";
import type * as gtmMaya_evidenceGuard from "../gtmMaya/evidenceGuard.js";
import type * as gtmMaya_experimentPlanner from "../gtmMaya/experimentPlanner.js";
import type * as gtmMaya_experimentStats from "../gtmMaya/experimentStats.js";
import type * as gtmMaya_experiments from "../gtmMaya/experiments.js";
import type * as gtmMaya_formatIntel from "../gtmMaya/formatIntel.js";
import type * as gtmMaya_intentStrike from "../gtmMaya/intentStrike.js";
import type * as gtmMaya_judgeCardsBatch from "../gtmMaya/judgeCardsBatch.js";
import type * as gtmMaya_judgeChannel from "../gtmMaya/judgeChannel.js";
import type * as gtmMaya_livenessWatch from "../gtmMaya/livenessWatch.js";
import type * as gtmMaya_managerStore from "../gtmMaya/managerStore.js";
import type * as gtmMaya_mediaAssets from "../gtmMaya/mediaAssets.js";
import type * as gtmMaya_memoryLedger from "../gtmMaya/memoryLedger.js";
import type * as gtmMaya_mineCommentTrees from "../gtmMaya/mineCommentTrees.js";
import type * as gtmMaya_missionActions from "../gtmMaya/missionActions.js";
import type * as gtmMaya_missionBoard from "../gtmMaya/missionBoard.js";
import type * as gtmMaya_missionControl from "../gtmMaya/missionControl.js";
import type * as gtmMaya_openclaw_conversationCapture from "../gtmMaya/openclaw/conversationCapture.js";
import type * as gtmMaya_openclaw_hookClient from "../gtmMaya/openclaw/hookClient.js";
import type * as gtmMaya_openclaw_inboundCallback from "../gtmMaya/openclaw/inboundCallback.js";
import type * as gtmMaya_openclaw_llmGateway from "../gtmMaya/openclaw/llmGateway.js";
import type * as gtmMaya_openclaw_managerCallbacks from "../gtmMaya/openclaw/managerCallbacks.js";
import type * as gtmMaya_openclaw_planCallbacks from "../gtmMaya/openclaw/planCallbacks.js";
import type * as gtmMaya_openclaw_pulseCallbacks from "../gtmMaya/openclaw/pulseCallbacks.js";
import type * as gtmMaya_openclaw_traceCapture from "../gtmMaya/openclaw/traceCapture.js";
import type * as gtmMaya_openrouterSpend from "../gtmMaya/openrouterSpend.js";
import type * as gtmMaya_outboundFirewall from "../gtmMaya/outboundFirewall.js";
import type * as gtmMaya_phase2Trigger from "../gtmMaya/phase2Trigger.js";
import type * as gtmMaya_planDoc from "../gtmMaya/planDoc.js";
import type * as gtmMaya_planGtm from "../gtmMaya/planGtm.js";
import type * as gtmMaya_platformAlgo from "../gtmMaya/platformAlgo.js";
import type * as gtmMaya_platformIntelligence from "../gtmMaya/platformIntelligence.js";
import type * as gtmMaya_platformWorkers from "../gtmMaya/platformWorkers.js";
import type * as gtmMaya_postResults from "../gtmMaya/postResults.js";
import type * as gtmMaya_privateBeta from "../gtmMaya/privateBeta.js";
import type * as gtmMaya_productPicture from "../gtmMaya/productPicture.js";
import type * as gtmMaya_productionReadiness from "../gtmMaya/productionReadiness.js";
import type * as gtmMaya_productionReality from "../gtmMaya/productionReality.js";
import type * as gtmMaya_providerPricing from "../gtmMaya/providerPricing.js";
import type * as gtmMaya_publishEngine from "../gtmMaya/publishEngine.js";
import type * as gtmMaya_publishWorkflow from "../gtmMaya/publishWorkflow.js";
import type * as gtmMaya_queryExpansion from "../gtmMaya/queryExpansion.js";
import type * as gtmMaya_recordPublished from "../gtmMaya/recordPublished.js";
import type * as gtmMaya_researchLifecycle from "../gtmMaya/researchLifecycle.js";
import type * as gtmMaya_researchQueryBuilder from "../gtmMaya/researchQueryBuilder.js";
import type * as gtmMaya_researchQueryRunner from "../gtmMaya/researchQueryRunner.js";
import type * as gtmMaya_researchResults from "../gtmMaya/researchResults.js";
import type * as gtmMaya_researchTasks from "../gtmMaya/researchTasks.js";
import type * as gtmMaya_researchWorker from "../gtmMaya/researchWorker.js";
import type * as gtmMaya_resultsLoop from "../gtmMaya/resultsLoop.js";
import type * as gtmMaya_scrapeCreatorsGtmResearch from "../gtmMaya/scrapeCreatorsGtmResearch.js";
import type * as gtmMaya_spendKill from "../gtmMaya/spendKill.js";
import type * as gtmMaya_steering from "../gtmMaya/steering.js";
import type * as gtmMaya_strategicDiagnosis from "../gtmMaya/strategicDiagnosis.js";
import type * as gtmMaya_strategyJudge from "../gtmMaya/strategyJudge.js";
import type * as gtmMaya_synthesisDelivery from "../gtmMaya/synthesisDelivery.js";
import type * as gtmMaya_targetList from "../gtmMaya/targetList.js";
import type * as gtmMaya_telegramBotPerTenant from "../gtmMaya/telegramBotPerTenant.js";
import type * as gtmMaya_telegramConfirm from "../gtmMaya/telegramConfirm.js";
import type * as gtmMaya_telegramHandoff from "../gtmMaya/telegramHandoff.js";
import type * as gtmMaya_telegramPairing from "../gtmMaya/telegramPairing.js";
import type * as gtmMaya_telegramWebhook from "../gtmMaya/telegramWebhook.js";
import type * as gtmMaya_tiktokWarmup from "../gtmMaya/tiktokWarmup.js";
import type * as gtmMaya_voiceProfile from "../gtmMaya/voiceProfile.js";
import type * as gtmMaya_walkthrough from "../gtmMaya/walkthrough.js";
import type * as gtmMaya_watermarks from "../gtmMaya/watermarks.js";
import type * as gtmMaya_webSearch from "../gtmMaya/webSearch.js";
import type * as gtmMaya_workspaceMutator from "../gtmMaya/workspaceMutator.js";
import type * as gtmMaya_zernioConnect from "../gtmMaya/zernioConnect.js";
import type * as gtmMaya_zernioReads from "../gtmMaya/zernioReads.js";
import type * as gtmMaya_zernioRoutes from "../gtmMaya/zernioRoutes.js";
import type * as gtmMaya_zernioWebhook from "../gtmMaya/zernioWebhook.js";
import type * as http from "../http.js";
import type * as integrations_appStore_playScraper from "../integrations/appStore/playScraper.js";
import type * as integrations_appStore_storeListing from "../integrations/appStore/storeListing.js";
import type * as integrations_composio_actions_calendar from "../integrations/composio/actions/calendar.js";
import type * as integrations_composio_actions_gmail from "../integrations/composio/actions/gmail.js";
import type * as integrations_composio_actions_index from "../integrations/composio/actions/index.js";
import type * as integrations_composio_actions_linkedin from "../integrations/composio/actions/linkedin.js";
import type * as integrations_composio_actions_stripe from "../integrations/composio/actions/stripe.js";
import type * as integrations_composio_actions_twitter from "../integrations/composio/actions/twitter.js";
import type * as integrations_composio_client from "../integrations/composio/client.js";
import type * as integrations_composio_oauth from "../integrations/composio/oauth.js";
import type * as integrations_composio_publishContent from "../integrations/composio/publishContent.js";
import type * as integrations_composio_universalRunner from "../integrations/composio/universalRunner.js";
import type * as integrations_creatify_client from "../integrations/creatify/client.js";
import type * as integrations_creatify_endpoints from "../integrations/creatify/endpoints.js";
import type * as integrations_creatify_types from "../integrations/creatify/types.js";
import type * as integrations_dataforseo_client from "../integrations/dataforseo/client.js";
import type * as integrations_gemini_groundedSearch from "../integrations/gemini/groundedSearch.js";
import type * as integrations_google_calendar from "../integrations/google/calendar.js";
import type * as integrations_google_gmail from "../integrations/google/gmail.js";
import type * as integrations_hackerNews_algoliaSearch from "../integrations/hackerNews/algoliaSearch.js";
import type * as integrations_openrouter_client from "../integrations/openrouter/client.js";
import type * as integrations_r2_client from "../integrations/r2/client.js";
import type * as integrations_r2_endpoints from "../integrations/r2/endpoints.js";
import type * as integrations_scrapeCreators___tests___fixtures_instagram from "../integrations/scrapeCreators/__tests__/fixtures/instagram.js";
import type * as integrations_scrapeCreators___tests___fixtures_linkedin from "../integrations/scrapeCreators/__tests__/fixtures/linkedin.js";
import type * as integrations_scrapeCreators___tests___fixtures_tiktok from "../integrations/scrapeCreators/__tests__/fixtures/tiktok.js";
import type * as integrations_scrapeCreators___tests___fixtures_x from "../integrations/scrapeCreators/__tests__/fixtures/x.js";
import type * as integrations_scrapeCreators___tests___fixtures_youtube from "../integrations/scrapeCreators/__tests__/fixtures/youtube.js";
import type * as integrations_scrapeCreators_cache from "../integrations/scrapeCreators/cache.js";
import type * as integrations_scrapeCreators_client from "../integrations/scrapeCreators/client.js";
import type * as integrations_scrapeCreators_deps from "../integrations/scrapeCreators/deps.js";
import type * as integrations_scrapeCreators_endpoints from "../integrations/scrapeCreators/endpoints.js";
import type * as integrations_scrapeCreators_normalize from "../integrations/scrapeCreators/normalize.js";
import type * as integrations_scrapeCreators_platforms_instagram from "../integrations/scrapeCreators/platforms/instagram.js";
import type * as integrations_scrapeCreators_platforms_linkedin from "../integrations/scrapeCreators/platforms/linkedin.js";
import type * as integrations_scrapeCreators_platforms_tiktok from "../integrations/scrapeCreators/platforms/tiktok.js";
import type * as integrations_scrapeCreators_platforms_x from "../integrations/scrapeCreators/platforms/x.js";
import type * as integrations_scrapeCreators_platforms_youtube from "../integrations/scrapeCreators/platforms/youtube.js";
import type * as integrations_scrapeCreators_schemas from "../integrations/scrapeCreators/schemas.js";
import type * as integrations_scrapeCreators_verifyHandle from "../integrations/scrapeCreators/verifyHandle.js";
import type * as integrations_telegram_client from "../integrations/telegram/client.js";
import type * as integrations_telegram_sendDirectMessage from "../integrations/telegram/sendDirectMessage.js";
import type * as integrations_twitterApiIo_endpoints from "../integrations/twitterApiIo/endpoints.js";
import type * as integrations_twitterApiIo_twitterSearch from "../integrations/twitterApiIo/twitterSearch.js";
import type * as integrations_videoSynthWorker_client from "../integrations/videoSynthWorker/client.js";
import type * as integrations_zernio_client from "../integrations/zernio/client.js";
import type * as integrations_zernio_endpoints from "../integrations/zernio/endpoints.js";
import type * as integrations_zernio_publish from "../integrations/zernio/publish.js";
import type * as integrations_zernio_types from "../integrations/zernio/types.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_flyClient from "../lib/flyClient.js";
import type * as lib_planFeatures from "../lib/planFeatures.js";
import type * as lib_posthog from "../lib/posthog.js";
import type * as lib_usageEvents from "../lib/usageEvents.js";
import type * as lib_webhookSecret from "../lib/webhookSecret.js";
import type * as maya_archive from "../maya/archive.js";
import type * as maya_assetClassifier from "../maya/assetClassifier.js";
import type * as maya_assetFloor from "../maya/assetFloor.js";
import type * as maya_attribution from "../maya/attribution.js";
import type * as maya_audience from "../maya/audience.js";
import type * as maya_benchmarks from "../maya/benchmarks.js";
import type * as maya_brandKit from "../maya/brandKit.js";
import type * as maya_breaker from "../maya/breaker.js";
import type * as maya_buyerMap from "../maya/buyerMap.js";
import type * as maya_cadence from "../maya/cadence.js";
import type * as maya_carousel from "../maya/carousel.js";
import type * as maya_channels from "../maya/channels.js";
import type * as maya_checkpoint from "../maya/checkpoint.js";
import type * as maya_cogs from "../maya/cogs.js";
import type * as maya_competitors from "../maya/competitors.js";
import type * as maya_complaints from "../maya/complaints.js";
import type * as maya_cringeEval from "../maya/cringeEval.js";
import type * as maya_crosspost from "../maya/crosspost.js";
import type * as maya_dailyReport from "../maya/dailyReport.js";
import type * as maya_dashboard from "../maya/dashboard.js";
import type * as maya_dataExport from "../maya/dataExport.js";
import type * as maya_dayPlan from "../maya/dayPlan.js";
import type * as maya_delivery from "../maya/delivery.js";
import type * as maya_demo from "../maya/demo.js";
import type * as maya_deploy from "../maya/deploy.js";
import type * as maya_directiveGate from "../maya/directiveGate.js";
import type * as maya_directives from "../maya/directives.js";
import type * as maya_drafts from "../maya/drafts.js";
import type * as maya_embeddings from "../maya/embeddings.js";
import type * as maya_experiments from "../maya/experiments.js";
import type * as maya_formats from "../maya/formats.js";
import type * as maya_handoff from "../maya/handoff.js";
import type * as maya_hooks from "../maya/hooks.js";
import type * as maya_ideas from "../maya/ideas.js";
import type * as maya_imagery from "../maya/imagery.js";
import type * as maya_inbox from "../maya/inbox.js";
import type * as maya_jobs from "../maya/jobs.js";
import type * as maya_ladder from "../maya/ladder.js";
import type * as maya_learnBusiness from "../maya/learnBusiness.js";
import type * as maya_liveness from "../maya/liveness.js";
import type * as maya_llm from "../maya/llm.js";
import type * as maya_media from "../maya/media.js";
import type * as maya_messages from "../maya/messages.js";
import type * as maya_metrics from "../maya/metrics.js";
import type * as maya_onramp from "../maya/onramp.js";
import type * as maya_outbound from "../maya/outbound.js";
import type * as maya_pairing from "../maya/pairing.js";
import type * as maya_plainLanguage from "../maya/plainLanguage.js";
import type * as maya_planFeatures from "../maya/planFeatures.js";
import type * as maya_preSpendGate from "../maya/preSpendGate.js";
import type * as maya_preflight from "../maya/preflight.js";
import type * as maya_productTruth from "../maya/productTruth.js";
import type * as maya_publish from "../maya/publish.js";
import type * as maya_publishDecision from "../maya/publishDecision.js";
import type * as maya_quality from "../maya/quality.js";
import type * as maya_relevance from "../maya/relevance.js";
import type * as maya_scheduler from "../maya/scheduler.js";
import type * as maya_scroll from "../maya/scroll.js";
import type * as maya_setup from "../maya/setup.js";
import type * as maya_slides from "../maya/slides.js";
import type * as maya_spendCeiling from "../maya/spendCeiling.js";
import type * as maya_strategy from "../maya/strategy.js";
import type * as maya_telegram from "../maya/telegram.js";
import type * as maya_telegramFiles from "../maya/telegramFiles.js";
import type * as maya_tells from "../maya/tells.js";
import type * as maya_tiktokConsent from "../maya/tiktokConsent.js";
import type * as maya_traceability from "../maya/traceability.js";
import type * as maya_trends from "../maya/trends.js";
import type * as maya_voice from "../maya/voice.js";
import type * as maya_voiceCorpus from "../maya/voiceCorpus.js";
import type * as maya_watchers from "../maya/watchers.js";
import type * as maya_weeklyReport from "../maya/weeklyReport.js";
import type * as maya_widerWorld from "../maya/widerWorld.js";
import type * as maya_zernioCapability from "../maya/zernioCapability.js";
import type * as migrations_backfillPlacementIdea from "../migrations/backfillPlacementIdea.js";
import type * as migrations_coachManagerPlanRename from "../migrations/coachManagerPlanRename.js";
import type * as migrations_recapDayKeyToFounderTimezone from "../migrations/recapDayKeyToFounderTimezone.js";
import type * as onboarding_gtm_deployMayaGtm from "../onboarding/gtm/deployMayaGtm.js";
import type * as queries_admin_usage from "../queries/admin/usage.js";
import type * as smokeFixtures_cronHeartbeat from "../smokeFixtures/cronHeartbeat.js";
import type * as vendorSmoke_drift from "../vendorSmoke/drift.js";
import type * as vendorSmoke_execute from "../vendorSmoke/execute.js";
import type * as vendorSmoke_registry from "../vendorSmoke/registry.js";
import type * as vendorSmoke_report from "../vendorSmoke/report.js";
import type * as vendorSmoke_runner from "../vendorSmoke/runner.js";
import type * as vendorSmoke_types from "../vendorSmoke/types.js";
import type * as waitlist_mayaProductWaitlist from "../waitlist/mayaProductWaitlist.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_admin/realWorldDeployGtm": typeof _admin_realWorldDeployGtm;
  "_admin/zernioLiveSmoke": typeof _admin_zernioLiveSmoke;
  accountDeletion: typeof accountDeletion;
  admin: typeof admin;
  "agents/modelRouter/logCall": typeof agents_modelRouter_logCall;
  "agents/modelRouter/maya": typeof agents_modelRouter_maya;
  "agents/modelRouter/openRouterClient": typeof agents_modelRouter_openRouterClient;
  "agents/modelRouter/taskTags": typeof agents_modelRouter_taskTags;
  "agents/packs/maya/bundledPlugin": typeof agents_packs_maya_bundledPlugin;
  "agents/packs/maya/bundledSkills": typeof agents_packs_maya_bundledSkills;
  "agents/packs/maya/generators": typeof agents_packs_maya_generators;
  "agents/packs/maya_gtm/bundledGtmPlugin": typeof agents_packs_maya_gtm_bundledGtmPlugin;
  "agents/packs/maya_gtm/bundledLocalSkills": typeof agents_packs_maya_gtm_bundledLocalSkills;
  "agents/packs/maya_gtm/bundledPlaybook": typeof agents_packs_maya_gtm_bundledPlaybook;
  "agents/packs/maya_gtm/generators": typeof agents_packs_maya_gtm_generators;
  "agents/packs/maya_gtm/pinnedClawhubSkills": typeof agents_packs_maya_gtm_pinnedClawhubSkills;
  "billing/checkout": typeof billing_checkout;
  "billing/gtmBilling": typeof billing_gtmBilling;
  "billing/portal": typeof billing_portal;
  "billing/priceIds": typeof billing_priceIds;
  "billing/stripeClient": typeof billing_stripeClient;
  "billing/stripeWebhookHttp": typeof billing_stripeWebhookHttp;
  "billing/webhook": typeof billing_webhook;
  creators: typeof creators;
  crons: typeof crons;
  "founder/dashboard": typeof founder_dashboard;
  "founder/fleetHealth": typeof founder_fleetHealth;
  "gtmMaya/accountLifecycle": typeof gtmMaya_accountLifecycle;
  "gtmMaya/agentLifecycle": typeof gtmMaya_agentLifecycle;
  "gtmMaya/appInspector": typeof gtmMaya_appInspector;
  "gtmMaya/approvalPublishing": typeof gtmMaya_approvalPublishing;
  "gtmMaya/archetypeBrain": typeof gtmMaya_archetypeBrain;
  "gtmMaya/attribution": typeof gtmMaya_attribution;
  "gtmMaya/autonomyPolicy": typeof gtmMaya_autonomyPolicy;
  "gtmMaya/betaGuards": typeof gtmMaya_betaGuards;
  "gtmMaya/calendarOAuth": typeof gtmMaya_calendarOAuth;
  "gtmMaya/calendarPlan": typeof gtmMaya_calendarPlan;
  "gtmMaya/calendarWrite": typeof gtmMaya_calendarWrite;
  "gtmMaya/channelAgents": typeof gtmMaya_channelAgents;
  "gtmMaya/channelScoring": typeof gtmMaya_channelScoring;
  "gtmMaya/channelSelection": typeof gtmMaya_channelSelection;
  "gtmMaya/channelWarmth": typeof gtmMaya_channelWarmth;
  "gtmMaya/contentQuality": typeof gtmMaya_contentQuality;
  "gtmMaya/contentReview": typeof gtmMaya_contentReview;
  "gtmMaya/conversionPing": typeof gtmMaya_conversionPing;
  "gtmMaya/costCap": typeof gtmMaya_costCap;
  "gtmMaya/costLedger": typeof gtmMaya_costLedger;
  "gtmMaya/creatifyVideo": typeof gtmMaya_creatifyVideo;
  "gtmMaya/creativeBudgetGate": typeof gtmMaya_creativeBudgetGate;
  "gtmMaya/deepLink": typeof gtmMaya_deepLink;
  "gtmMaya/deliveryFailures": typeof gtmMaya_deliveryFailures;
  "gtmMaya/demandIntel": typeof gtmMaya_demandIntel;
  "gtmMaya/discoveryBudgetGate": typeof gtmMaya_discoveryBudgetGate;
  "gtmMaya/distributionMotions": typeof gtmMaya_distributionMotions;
  "gtmMaya/engagementLedger": typeof gtmMaya_engagementLedger;
  "gtmMaya/evidenceGuard": typeof gtmMaya_evidenceGuard;
  "gtmMaya/experimentPlanner": typeof gtmMaya_experimentPlanner;
  "gtmMaya/experimentStats": typeof gtmMaya_experimentStats;
  "gtmMaya/experiments": typeof gtmMaya_experiments;
  "gtmMaya/formatIntel": typeof gtmMaya_formatIntel;
  "gtmMaya/intentStrike": typeof gtmMaya_intentStrike;
  "gtmMaya/judgeCardsBatch": typeof gtmMaya_judgeCardsBatch;
  "gtmMaya/judgeChannel": typeof gtmMaya_judgeChannel;
  "gtmMaya/livenessWatch": typeof gtmMaya_livenessWatch;
  "gtmMaya/managerStore": typeof gtmMaya_managerStore;
  "gtmMaya/mediaAssets": typeof gtmMaya_mediaAssets;
  "gtmMaya/memoryLedger": typeof gtmMaya_memoryLedger;
  "gtmMaya/mineCommentTrees": typeof gtmMaya_mineCommentTrees;
  "gtmMaya/missionActions": typeof gtmMaya_missionActions;
  "gtmMaya/missionBoard": typeof gtmMaya_missionBoard;
  "gtmMaya/missionControl": typeof gtmMaya_missionControl;
  "gtmMaya/openclaw/conversationCapture": typeof gtmMaya_openclaw_conversationCapture;
  "gtmMaya/openclaw/hookClient": typeof gtmMaya_openclaw_hookClient;
  "gtmMaya/openclaw/inboundCallback": typeof gtmMaya_openclaw_inboundCallback;
  "gtmMaya/openclaw/llmGateway": typeof gtmMaya_openclaw_llmGateway;
  "gtmMaya/openclaw/managerCallbacks": typeof gtmMaya_openclaw_managerCallbacks;
  "gtmMaya/openclaw/planCallbacks": typeof gtmMaya_openclaw_planCallbacks;
  "gtmMaya/openclaw/pulseCallbacks": typeof gtmMaya_openclaw_pulseCallbacks;
  "gtmMaya/openclaw/traceCapture": typeof gtmMaya_openclaw_traceCapture;
  "gtmMaya/openrouterSpend": typeof gtmMaya_openrouterSpend;
  "gtmMaya/outboundFirewall": typeof gtmMaya_outboundFirewall;
  "gtmMaya/phase2Trigger": typeof gtmMaya_phase2Trigger;
  "gtmMaya/planDoc": typeof gtmMaya_planDoc;
  "gtmMaya/planGtm": typeof gtmMaya_planGtm;
  "gtmMaya/platformAlgo": typeof gtmMaya_platformAlgo;
  "gtmMaya/platformIntelligence": typeof gtmMaya_platformIntelligence;
  "gtmMaya/platformWorkers": typeof gtmMaya_platformWorkers;
  "gtmMaya/postResults": typeof gtmMaya_postResults;
  "gtmMaya/privateBeta": typeof gtmMaya_privateBeta;
  "gtmMaya/productPicture": typeof gtmMaya_productPicture;
  "gtmMaya/productionReadiness": typeof gtmMaya_productionReadiness;
  "gtmMaya/productionReality": typeof gtmMaya_productionReality;
  "gtmMaya/providerPricing": typeof gtmMaya_providerPricing;
  "gtmMaya/publishEngine": typeof gtmMaya_publishEngine;
  "gtmMaya/publishWorkflow": typeof gtmMaya_publishWorkflow;
  "gtmMaya/queryExpansion": typeof gtmMaya_queryExpansion;
  "gtmMaya/recordPublished": typeof gtmMaya_recordPublished;
  "gtmMaya/researchLifecycle": typeof gtmMaya_researchLifecycle;
  "gtmMaya/researchQueryBuilder": typeof gtmMaya_researchQueryBuilder;
  "gtmMaya/researchQueryRunner": typeof gtmMaya_researchQueryRunner;
  "gtmMaya/researchResults": typeof gtmMaya_researchResults;
  "gtmMaya/researchTasks": typeof gtmMaya_researchTasks;
  "gtmMaya/researchWorker": typeof gtmMaya_researchWorker;
  "gtmMaya/resultsLoop": typeof gtmMaya_resultsLoop;
  "gtmMaya/scrapeCreatorsGtmResearch": typeof gtmMaya_scrapeCreatorsGtmResearch;
  "gtmMaya/spendKill": typeof gtmMaya_spendKill;
  "gtmMaya/steering": typeof gtmMaya_steering;
  "gtmMaya/strategicDiagnosis": typeof gtmMaya_strategicDiagnosis;
  "gtmMaya/strategyJudge": typeof gtmMaya_strategyJudge;
  "gtmMaya/synthesisDelivery": typeof gtmMaya_synthesisDelivery;
  "gtmMaya/targetList": typeof gtmMaya_targetList;
  "gtmMaya/telegramBotPerTenant": typeof gtmMaya_telegramBotPerTenant;
  "gtmMaya/telegramConfirm": typeof gtmMaya_telegramConfirm;
  "gtmMaya/telegramHandoff": typeof gtmMaya_telegramHandoff;
  "gtmMaya/telegramPairing": typeof gtmMaya_telegramPairing;
  "gtmMaya/telegramWebhook": typeof gtmMaya_telegramWebhook;
  "gtmMaya/tiktokWarmup": typeof gtmMaya_tiktokWarmup;
  "gtmMaya/voiceProfile": typeof gtmMaya_voiceProfile;
  "gtmMaya/walkthrough": typeof gtmMaya_walkthrough;
  "gtmMaya/watermarks": typeof gtmMaya_watermarks;
  "gtmMaya/webSearch": typeof gtmMaya_webSearch;
  "gtmMaya/workspaceMutator": typeof gtmMaya_workspaceMutator;
  "gtmMaya/zernioConnect": typeof gtmMaya_zernioConnect;
  "gtmMaya/zernioReads": typeof gtmMaya_zernioReads;
  "gtmMaya/zernioRoutes": typeof gtmMaya_zernioRoutes;
  "gtmMaya/zernioWebhook": typeof gtmMaya_zernioWebhook;
  http: typeof http;
  "integrations/appStore/playScraper": typeof integrations_appStore_playScraper;
  "integrations/appStore/storeListing": typeof integrations_appStore_storeListing;
  "integrations/composio/actions/calendar": typeof integrations_composio_actions_calendar;
  "integrations/composio/actions/gmail": typeof integrations_composio_actions_gmail;
  "integrations/composio/actions/index": typeof integrations_composio_actions_index;
  "integrations/composio/actions/linkedin": typeof integrations_composio_actions_linkedin;
  "integrations/composio/actions/stripe": typeof integrations_composio_actions_stripe;
  "integrations/composio/actions/twitter": typeof integrations_composio_actions_twitter;
  "integrations/composio/client": typeof integrations_composio_client;
  "integrations/composio/oauth": typeof integrations_composio_oauth;
  "integrations/composio/publishContent": typeof integrations_composio_publishContent;
  "integrations/composio/universalRunner": typeof integrations_composio_universalRunner;
  "integrations/creatify/client": typeof integrations_creatify_client;
  "integrations/creatify/endpoints": typeof integrations_creatify_endpoints;
  "integrations/creatify/types": typeof integrations_creatify_types;
  "integrations/dataforseo/client": typeof integrations_dataforseo_client;
  "integrations/gemini/groundedSearch": typeof integrations_gemini_groundedSearch;
  "integrations/google/calendar": typeof integrations_google_calendar;
  "integrations/google/gmail": typeof integrations_google_gmail;
  "integrations/hackerNews/algoliaSearch": typeof integrations_hackerNews_algoliaSearch;
  "integrations/openrouter/client": typeof integrations_openrouter_client;
  "integrations/r2/client": typeof integrations_r2_client;
  "integrations/r2/endpoints": typeof integrations_r2_endpoints;
  "integrations/scrapeCreators/__tests__/fixtures/instagram": typeof integrations_scrapeCreators___tests___fixtures_instagram;
  "integrations/scrapeCreators/__tests__/fixtures/linkedin": typeof integrations_scrapeCreators___tests___fixtures_linkedin;
  "integrations/scrapeCreators/__tests__/fixtures/tiktok": typeof integrations_scrapeCreators___tests___fixtures_tiktok;
  "integrations/scrapeCreators/__tests__/fixtures/x": typeof integrations_scrapeCreators___tests___fixtures_x;
  "integrations/scrapeCreators/__tests__/fixtures/youtube": typeof integrations_scrapeCreators___tests___fixtures_youtube;
  "integrations/scrapeCreators/cache": typeof integrations_scrapeCreators_cache;
  "integrations/scrapeCreators/client": typeof integrations_scrapeCreators_client;
  "integrations/scrapeCreators/deps": typeof integrations_scrapeCreators_deps;
  "integrations/scrapeCreators/endpoints": typeof integrations_scrapeCreators_endpoints;
  "integrations/scrapeCreators/normalize": typeof integrations_scrapeCreators_normalize;
  "integrations/scrapeCreators/platforms/instagram": typeof integrations_scrapeCreators_platforms_instagram;
  "integrations/scrapeCreators/platforms/linkedin": typeof integrations_scrapeCreators_platforms_linkedin;
  "integrations/scrapeCreators/platforms/tiktok": typeof integrations_scrapeCreators_platforms_tiktok;
  "integrations/scrapeCreators/platforms/x": typeof integrations_scrapeCreators_platforms_x;
  "integrations/scrapeCreators/platforms/youtube": typeof integrations_scrapeCreators_platforms_youtube;
  "integrations/scrapeCreators/schemas": typeof integrations_scrapeCreators_schemas;
  "integrations/scrapeCreators/verifyHandle": typeof integrations_scrapeCreators_verifyHandle;
  "integrations/telegram/client": typeof integrations_telegram_client;
  "integrations/telegram/sendDirectMessage": typeof integrations_telegram_sendDirectMessage;
  "integrations/twitterApiIo/endpoints": typeof integrations_twitterApiIo_endpoints;
  "integrations/twitterApiIo/twitterSearch": typeof integrations_twitterApiIo_twitterSearch;
  "integrations/videoSynthWorker/client": typeof integrations_videoSynthWorker_client;
  "integrations/zernio/client": typeof integrations_zernio_client;
  "integrations/zernio/endpoints": typeof integrations_zernio_endpoints;
  "integrations/zernio/publish": typeof integrations_zernio_publish;
  "integrations/zernio/types": typeof integrations_zernio_types;
  "lib/encryption": typeof lib_encryption;
  "lib/flyClient": typeof lib_flyClient;
  "lib/planFeatures": typeof lib_planFeatures;
  "lib/posthog": typeof lib_posthog;
  "lib/usageEvents": typeof lib_usageEvents;
  "lib/webhookSecret": typeof lib_webhookSecret;
  "maya/archive": typeof maya_archive;
  "maya/assetClassifier": typeof maya_assetClassifier;
  "maya/assetFloor": typeof maya_assetFloor;
  "maya/attribution": typeof maya_attribution;
  "maya/audience": typeof maya_audience;
  "maya/benchmarks": typeof maya_benchmarks;
  "maya/brandKit": typeof maya_brandKit;
  "maya/breaker": typeof maya_breaker;
  "maya/buyerMap": typeof maya_buyerMap;
  "maya/cadence": typeof maya_cadence;
  "maya/carousel": typeof maya_carousel;
  "maya/channels": typeof maya_channels;
  "maya/checkpoint": typeof maya_checkpoint;
  "maya/cogs": typeof maya_cogs;
  "maya/competitors": typeof maya_competitors;
  "maya/complaints": typeof maya_complaints;
  "maya/cringeEval": typeof maya_cringeEval;
  "maya/crosspost": typeof maya_crosspost;
  "maya/dailyReport": typeof maya_dailyReport;
  "maya/dashboard": typeof maya_dashboard;
  "maya/dataExport": typeof maya_dataExport;
  "maya/dayPlan": typeof maya_dayPlan;
  "maya/delivery": typeof maya_delivery;
  "maya/demo": typeof maya_demo;
  "maya/deploy": typeof maya_deploy;
  "maya/directiveGate": typeof maya_directiveGate;
  "maya/directives": typeof maya_directives;
  "maya/drafts": typeof maya_drafts;
  "maya/embeddings": typeof maya_embeddings;
  "maya/experiments": typeof maya_experiments;
  "maya/formats": typeof maya_formats;
  "maya/handoff": typeof maya_handoff;
  "maya/hooks": typeof maya_hooks;
  "maya/ideas": typeof maya_ideas;
  "maya/imagery": typeof maya_imagery;
  "maya/inbox": typeof maya_inbox;
  "maya/jobs": typeof maya_jobs;
  "maya/ladder": typeof maya_ladder;
  "maya/learnBusiness": typeof maya_learnBusiness;
  "maya/liveness": typeof maya_liveness;
  "maya/llm": typeof maya_llm;
  "maya/media": typeof maya_media;
  "maya/messages": typeof maya_messages;
  "maya/metrics": typeof maya_metrics;
  "maya/onramp": typeof maya_onramp;
  "maya/outbound": typeof maya_outbound;
  "maya/pairing": typeof maya_pairing;
  "maya/plainLanguage": typeof maya_plainLanguage;
  "maya/planFeatures": typeof maya_planFeatures;
  "maya/preSpendGate": typeof maya_preSpendGate;
  "maya/preflight": typeof maya_preflight;
  "maya/productTruth": typeof maya_productTruth;
  "maya/publish": typeof maya_publish;
  "maya/publishDecision": typeof maya_publishDecision;
  "maya/quality": typeof maya_quality;
  "maya/relevance": typeof maya_relevance;
  "maya/scheduler": typeof maya_scheduler;
  "maya/scroll": typeof maya_scroll;
  "maya/setup": typeof maya_setup;
  "maya/slides": typeof maya_slides;
  "maya/spendCeiling": typeof maya_spendCeiling;
  "maya/strategy": typeof maya_strategy;
  "maya/telegram": typeof maya_telegram;
  "maya/telegramFiles": typeof maya_telegramFiles;
  "maya/tells": typeof maya_tells;
  "maya/tiktokConsent": typeof maya_tiktokConsent;
  "maya/traceability": typeof maya_traceability;
  "maya/trends": typeof maya_trends;
  "maya/voice": typeof maya_voice;
  "maya/voiceCorpus": typeof maya_voiceCorpus;
  "maya/watchers": typeof maya_watchers;
  "maya/weeklyReport": typeof maya_weeklyReport;
  "maya/widerWorld": typeof maya_widerWorld;
  "maya/zernioCapability": typeof maya_zernioCapability;
  "migrations/backfillPlacementIdea": typeof migrations_backfillPlacementIdea;
  "migrations/coachManagerPlanRename": typeof migrations_coachManagerPlanRename;
  "migrations/recapDayKeyToFounderTimezone": typeof migrations_recapDayKeyToFounderTimezone;
  "onboarding/gtm/deployMayaGtm": typeof onboarding_gtm_deployMayaGtm;
  "queries/admin/usage": typeof queries_admin_usage;
  "smokeFixtures/cronHeartbeat": typeof smokeFixtures_cronHeartbeat;
  "vendorSmoke/drift": typeof vendorSmoke_drift;
  "vendorSmoke/execute": typeof vendorSmoke_execute;
  "vendorSmoke/registry": typeof vendorSmoke_registry;
  "vendorSmoke/report": typeof vendorSmoke_report;
  "vendorSmoke/runner": typeof vendorSmoke_runner;
  "vendorSmoke/types": typeof vendorSmoke_types;
  "waitlist/mayaProductWaitlist": typeof waitlist_mayaProductWaitlist;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
