/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _admin_peekState from "../_admin/peekState.js";
import type * as _admin_realWorldDeploy from "../_admin/realWorldDeploy.js";
import type * as _admin_realWorldDeployGtm from "../_admin/realWorldDeployGtm.js";
import type * as _admin_zernioLiveSmoke from "../_admin/zernioLiveSmoke.js";
import type * as _test_serviceFixtures from "../_test/serviceFixtures.js";
import type * as accountDeletion from "../accountDeletion.js";
import type * as admin from "../admin.js";
import type * as agents_modelRouter_logCall from "../agents/modelRouter/logCall.js";
import type * as agents_modelRouter_maya from "../agents/modelRouter/maya.js";
import type * as agents_modelRouter_openRouterClient from "../agents/modelRouter/openRouterClient.js";
import type * as agents_modelRouter_taskTags from "../agents/modelRouter/taskTags.js";
import type * as agents_packs_maya_configGeneratorMaya from "../agents/packs/maya/configGeneratorMaya.js";
import type * as agents_packs_maya_serializeWorkspaceBundle from "../agents/packs/maya/serializeWorkspaceBundle.js";
import type * as agents_packs_maya_workspace_assembleWorkspaceBundle from "../agents/packs/maya/workspace/assembleWorkspaceBundle.js";
import type * as agents_packs_maya_workspace_buildCronJobsJson from "../agents/packs/maya/workspace/buildCronJobsJson.js";
import type * as agents_packs_maya_workspace_generateAgentsMd from "../agents/packs/maya/workspace/generateAgentsMd.js";
import type * as agents_packs_maya_workspace_generateBootMd from "../agents/packs/maya/workspace/generateBootMd.js";
import type * as agents_packs_maya_workspace_generateDreamingMd from "../agents/packs/maya/workspace/generateDreamingMd.js";
import type * as agents_packs_maya_workspace_generateHeartbeatMd from "../agents/packs/maya/workspace/generateHeartbeatMd.js";
import type * as agents_packs_maya_workspace_generateIdentityMd from "../agents/packs/maya/workspace/generateIdentityMd.js";
import type * as agents_packs_maya_workspace_generateMemoryMdSeed from "../agents/packs/maya/workspace/generateMemoryMdSeed.js";
import type * as agents_packs_maya_workspace_generateSoulMd from "../agents/packs/maya/workspace/generateSoulMd.js";
import type * as agents_packs_maya_workspace_generateToolsMd from "../agents/packs/maya/workspace/generateToolsMd.js";
import type * as agents_packs_maya_workspace_generateUserMd from "../agents/packs/maya/workspace/generateUserMd.js";
import type * as agents_packs_maya_workspace_skillsRegistry from "../agents/packs/maya/workspace/skillsRegistry.js";
import type * as agents_packs_maya_workspace_standingOrders from "../agents/packs/maya/workspace/standingOrders.js";
import type * as agents_packs_maya_workspace_types from "../agents/packs/maya/workspace/types.js";
import type * as agents_packs_maya_gtm_bundledGtmPlugin from "../agents/packs/maya_gtm/bundledGtmPlugin.js";
import type * as agents_packs_maya_gtm_bundledLocalSkills from "../agents/packs/maya_gtm/bundledLocalSkills.js";
import type * as agents_packs_maya_gtm_bundledPlaybook from "../agents/packs/maya_gtm/bundledPlaybook.js";
import type * as agents_packs_maya_gtm_generators from "../agents/packs/maya_gtm/generators.js";
import type * as agents_packs_maya_gtm_pinnedClawhubSkills from "../agents/packs/maya_gtm/pinnedClawhubSkills.js";
import type * as agents_packs_maya_service_anthropicSkillsManifest from "../agents/packs/maya_service/anthropicSkillsManifest.js";
import type * as agents_packs_maya_service_buildJobsJson from "../agents/packs/maya_service/buildJobsJson.js";
import type * as agents_packs_maya_service_clawhubManifest from "../agents/packs/maya_service/clawhubManifest.js";
import type * as agents_packs_maya_service_generateAgents from "../agents/packs/maya_service/generateAgents.js";
import type * as agents_packs_maya_service_generateBoot from "../agents/packs/maya_service/generateBoot.js";
import type * as agents_packs_maya_service_generateBusinessPicture from "../agents/packs/maya_service/generateBusinessPicture.js";
import type * as agents_packs_maya_service_generateDreaming from "../agents/packs/maya_service/generateDreaming.js";
import type * as agents_packs_maya_service_generateHeartbeat from "../agents/packs/maya_service/generateHeartbeat.js";
import type * as agents_packs_maya_service_generateMemorySeed from "../agents/packs/maya_service/generateMemorySeed.js";
import type * as agents_packs_maya_service_generateSoul from "../agents/packs/maya_service/generateSoul.js";
import type * as agents_packs_maya_service_generateTools from "../agents/packs/maya_service/generateTools.js";
import type * as agents_packs_maya_service_memoryWikiConfig from "../agents/packs/maya_service/memoryWikiConfig.js";
import type * as agents_packs_maya_service_runLearningsExtractor from "../agents/packs/maya_service/runLearningsExtractor.js";
import type * as agents_packs_maya_service_standingOrders from "../agents/packs/maya_service/standingOrders.js";
import type * as agents_packs_maya_service_types from "../agents/packs/maya_service/types.js";
import type * as agents_packs_maya_service_voiceCallConfig from "../agents/packs/maya_service/voiceCallConfig.js";
import type * as agents_packs_maya_service_wikiInitialPages from "../agents/packs/maya_service/wikiInitialPages.js";
import type * as agents_packs_riley_growth_clawhubManifest from "../agents/packs/riley_growth/clawhubManifest.js";
import type * as agents_packs_riley_growth_generators from "../agents/packs/riley_growth/generators.js";
import type * as billing_checkout from "../billing/checkout.js";
import type * as billing_gtmBilling from "../billing/gtmBilling.js";
import type * as billing_portal from "../billing/portal.js";
import type * as billing_priceIds from "../billing/priceIds.js";
import type * as billing_stripeClient from "../billing/stripeClient.js";
import type * as billing_webhook from "../billing/webhook.js";
import type * as businessReadiness from "../businessReadiness.js";
import type * as creatorMayaV0_backend from "../creatorMayaV0/backend.js";
import type * as creatorMayaV0_brandOutreach from "../creatorMayaV0/brandOutreach.js";
import type * as creatorMayaV0_calendarLookahead from "../creatorMayaV0/calendarLookahead.js";
import type * as creatorMayaV0_calendarScheduling from "../creatorMayaV0/calendarScheduling.js";
import type * as creatorMayaV0_dailyBrief from "../creatorMayaV0/dailyBrief.js";
import type * as creatorMayaV0_editingFingerprintObservations from "../creatorMayaV0/editingFingerprintObservations.js";
import type * as creatorMayaV0_mayaCalendarEvents from "../creatorMayaV0/mayaCalendarEvents.js";
import type * as creatorMayaV0_mediaAssets from "../creatorMayaV0/mediaAssets.js";
import type * as creatorMayaV0_onboardingFlow from "../creatorMayaV0/onboardingFlow.js";
import type * as creatorMayaV0_onboardingIntake from "../creatorMayaV0/onboardingIntake.js";
import type * as creatorMayaV0_openClawDeployGate from "../creatorMayaV0/openClawDeployGate.js";
import type * as creatorMayaV0_openClawMediaIngestHttp from "../creatorMayaV0/openClawMediaIngestHttp.js";
import type * as creatorMayaV0_pinnedClawhubSkills from "../creatorMayaV0/pinnedClawhubSkills.js";
import type * as creatorMayaV0_scope from "../creatorMayaV0/scope.js";
import type * as creatorMayaV0_tiering from "../creatorMayaV0/tiering.js";
import type * as creatorMayaV0_trendBenchmark from "../creatorMayaV0/trendBenchmark.js";
import type * as creatorMayaV0_uploadRenderedMediaHttp from "../creatorMayaV0/uploadRenderedMediaHttp.js";
import type * as creatorMayaV0_videoSampling from "../creatorMayaV0/videoSampling.js";
import type * as creatorMayaV0_workspaceManifest from "../creatorMayaV0/workspaceManifest.js";
import type * as creators from "../creators.js";
import type * as crons from "../crons.js";
import type * as dealTriage from "../dealTriage.js";
import type * as deals from "../deals.js";
import type * as founder_dashboard from "../founder/dashboard.js";
import type * as gbp_computeHealthScore from "../gbp/computeHealthScore.js";
import type * as gtmMaya_accountLifecycle from "../gtmMaya/accountLifecycle.js";
import type * as gtmMaya_agentLifecycle from "../gtmMaya/agentLifecycle.js";
import type * as gtmMaya_appInspector from "../gtmMaya/appInspector.js";
import type * as gtmMaya_approvalPublishing from "../gtmMaya/approvalPublishing.js";
import type * as gtmMaya_archetypeBrain from "../gtmMaya/archetypeBrain.js";
import type * as gtmMaya_attribution from "../gtmMaya/attribution.js";
import type * as gtmMaya_autonomyPolicy from "../gtmMaya/autonomyPolicy.js";
import type * as gtmMaya_betaGuards from "../gtmMaya/betaGuards.js";
import type * as gtmMaya_calendarOAuth from "../gtmMaya/calendarOAuth.js";
import type * as gtmMaya_calendarPlan from "../gtmMaya/calendarPlan.js";
import type * as gtmMaya_calendarWrite from "../gtmMaya/calendarWrite.js";
import type * as gtmMaya_channelAgents from "../gtmMaya/channelAgents.js";
import type * as gtmMaya_channelScoring from "../gtmMaya/channelScoring.js";
import type * as gtmMaya_channelSelection from "../gtmMaya/channelSelection.js";
import type * as gtmMaya_channelWarmth from "../gtmMaya/channelWarmth.js";
import type * as gtmMaya_coldStrike from "../gtmMaya/coldStrike.js";
import type * as gtmMaya_contentQuality from "../gtmMaya/contentQuality.js";
import type * as gtmMaya_contentReview from "../gtmMaya/contentReview.js";
import type * as gtmMaya_conversionPing from "../gtmMaya/conversionPing.js";
import type * as gtmMaya_costCap from "../gtmMaya/costCap.js";
import type * as gtmMaya_costLedger from "../gtmMaya/costLedger.js";
import type * as gtmMaya_creatifyVideo from "../gtmMaya/creatifyVideo.js";
import type * as gtmMaya_creativeBudgetGate from "../gtmMaya/creativeBudgetGate.js";
import type * as gtmMaya_dayPlanner from "../gtmMaya/dayPlanner.js";
import type * as gtmMaya_deepLink from "../gtmMaya/deepLink.js";
import type * as gtmMaya_deliveryFailures from "../gtmMaya/deliveryFailures.js";
import type * as gtmMaya_demandIntel from "../gtmMaya/demandIntel.js";
import type * as gtmMaya_discoveryBudgetGate from "../gtmMaya/discoveryBudgetGate.js";
import type * as gtmMaya_distributionMotions from "../gtmMaya/distributionMotions.js";
import type * as gtmMaya_engagementLedger from "../gtmMaya/engagementLedger.js";
import type * as gtmMaya_evidenceGuard from "../gtmMaya/evidenceGuard.js";
import type * as gtmMaya_experimentPlanner from "../gtmMaya/experimentPlanner.js";
import type * as gtmMaya_experimentStats from "../gtmMaya/experimentStats.js";
import type * as gtmMaya_experiments from "../gtmMaya/experiments.js";
import type * as gtmMaya_formatIntel from "../gtmMaya/formatIntel.js";
import type * as gtmMaya_intentStrike from "../gtmMaya/intentStrike.js";
import type * as gtmMaya_judgeCardsBatch from "../gtmMaya/judgeCardsBatch.js";
import type * as gtmMaya_judgeChannel from "../gtmMaya/judgeChannel.js";
import type * as gtmMaya_livenessWatch from "../gtmMaya/livenessWatch.js";
import type * as gtmMaya_managerStore from "../gtmMaya/managerStore.js";
import type * as gtmMaya_mediaAssets from "../gtmMaya/mediaAssets.js";
import type * as gtmMaya_memoryLedger from "../gtmMaya/memoryLedger.js";
import type * as gtmMaya_mineCommentTrees from "../gtmMaya/mineCommentTrees.js";
import type * as gtmMaya_missionBoard from "../gtmMaya/missionBoard.js";
import type * as gtmMaya_missionControl from "../gtmMaya/missionControl.js";
import type * as gtmMaya_openclaw_conversationCapture from "../gtmMaya/openclaw/conversationCapture.js";
import type * as gtmMaya_openclaw_hookClient from "../gtmMaya/openclaw/hookClient.js";
import type * as gtmMaya_openclaw_inboundCallback from "../gtmMaya/openclaw/inboundCallback.js";
import type * as gtmMaya_openclaw_llmGateway from "../gtmMaya/openclaw/llmGateway.js";
import type * as gtmMaya_openclaw_managerCallbacks from "../gtmMaya/openclaw/managerCallbacks.js";
import type * as gtmMaya_openclaw_planCallbacks from "../gtmMaya/openclaw/planCallbacks.js";
import type * as gtmMaya_openclaw_pulseCallbacks from "../gtmMaya/openclaw/pulseCallbacks.js";
import type * as gtmMaya_openclaw_traceCapture from "../gtmMaya/openclaw/traceCapture.js";
import type * as gtmMaya_openrouterSpend from "../gtmMaya/openrouterSpend.js";
import type * as gtmMaya_outboundFirewall from "../gtmMaya/outboundFirewall.js";
import type * as gtmMaya_phase2Trigger from "../gtmMaya/phase2Trigger.js";
import type * as gtmMaya_planGtm from "../gtmMaya/planGtm.js";
import type * as gtmMaya_platformAlgo from "../gtmMaya/platformAlgo.js";
import type * as gtmMaya_platformIntelligence from "../gtmMaya/platformIntelligence.js";
import type * as gtmMaya_platformWorkers from "../gtmMaya/platformWorkers.js";
import type * as gtmMaya_postResults from "../gtmMaya/postResults.js";
import type * as gtmMaya_privateBeta from "../gtmMaya/privateBeta.js";
import type * as gtmMaya_productPicture from "../gtmMaya/productPicture.js";
import type * as gtmMaya_productionReadiness from "../gtmMaya/productionReadiness.js";
import type * as gtmMaya_productionReality from "../gtmMaya/productionReality.js";
import type * as gtmMaya_providerPricing from "../gtmMaya/providerPricing.js";
import type * as gtmMaya_publishEngine from "../gtmMaya/publishEngine.js";
import type * as gtmMaya_publishWorkflow from "../gtmMaya/publishWorkflow.js";
import type * as gtmMaya_queryExpansion from "../gtmMaya/queryExpansion.js";
import type * as gtmMaya_recordPublished from "../gtmMaya/recordPublished.js";
import type * as gtmMaya_researchLifecycle from "../gtmMaya/researchLifecycle.js";
import type * as gtmMaya_researchQueryBuilder from "../gtmMaya/researchQueryBuilder.js";
import type * as gtmMaya_researchQueryRunner from "../gtmMaya/researchQueryRunner.js";
import type * as gtmMaya_researchResults from "../gtmMaya/researchResults.js";
import type * as gtmMaya_researchTasks from "../gtmMaya/researchTasks.js";
import type * as gtmMaya_researchWorker from "../gtmMaya/researchWorker.js";
import type * as gtmMaya_resultsLoop from "../gtmMaya/resultsLoop.js";
import type * as gtmMaya_scrapeCreatorsGtmResearch from "../gtmMaya/scrapeCreatorsGtmResearch.js";
import type * as gtmMaya_spendKill from "../gtmMaya/spendKill.js";
import type * as gtmMaya_steering from "../gtmMaya/steering.js";
import type * as gtmMaya_strategicDiagnosis from "../gtmMaya/strategicDiagnosis.js";
import type * as gtmMaya_strategyJudge from "../gtmMaya/strategyJudge.js";
import type * as gtmMaya_synthesisDelivery from "../gtmMaya/synthesisDelivery.js";
import type * as gtmMaya_targetList from "../gtmMaya/targetList.js";
import type * as gtmMaya_telegramBotPerTenant from "../gtmMaya/telegramBotPerTenant.js";
import type * as gtmMaya_telegramConfirm from "../gtmMaya/telegramConfirm.js";
import type * as gtmMaya_telegramHandoff from "../gtmMaya/telegramHandoff.js";
import type * as gtmMaya_telegramPairing from "../gtmMaya/telegramPairing.js";
import type * as gtmMaya_telegramWebhook from "../gtmMaya/telegramWebhook.js";
import type * as gtmMaya_tiktokWarmup from "../gtmMaya/tiktokWarmup.js";
import type * as gtmMaya_voiceProfile from "../gtmMaya/voiceProfile.js";
import type * as gtmMaya_walkthrough from "../gtmMaya/walkthrough.js";
import type * as gtmMaya_watermarks from "../gtmMaya/watermarks.js";
import type * as gtmMaya_webSearch from "../gtmMaya/webSearch.js";
import type * as gtmMaya_workspaceMutator from "../gtmMaya/workspaceMutator.js";
import type * as gtmMaya_zernioConnect from "../gtmMaya/zernioConnect.js";
import type * as gtmMaya_zernioReads from "../gtmMaya/zernioReads.js";
import type * as gtmMaya_zernioRoutes from "../gtmMaya/zernioRoutes.js";
import type * as gtmMaya_zernioWebhook from "../gtmMaya/zernioWebhook.js";
import type * as http from "../http.js";
import type * as integrations_aggregators_unified_client from "../integrations/aggregators/unified/client.js";
import type * as integrations_aggregators_unified_types from "../integrations/aggregators/unified/types.js";
import type * as integrations_apify_twitterScraper from "../integrations/apify/twitterScraper.js";
import type * as integrations_apollo_actions from "../integrations/apollo/actions.js";
import type * as integrations_apollo_client from "../integrations/apollo/client.js";
import type * as integrations_appStore_playScraper from "../integrations/appStore/playScraper.js";
import type * as integrations_appStore_storeListing from "../integrations/appStore/storeListing.js";
import type * as integrations_apple_caldav from "../integrations/apple/caldav.js";
import type * as integrations_composio_actions_calendar from "../integrations/composio/actions/calendar.js";
import type * as integrations_composio_actions_gmail from "../integrations/composio/actions/gmail.js";
import type * as integrations_composio_actions_index from "../integrations/composio/actions/index.js";
import type * as integrations_composio_actions_linkedin from "../integrations/composio/actions/linkedin.js";
import type * as integrations_composio_actions_stripe from "../integrations/composio/actions/stripe.js";
import type * as integrations_composio_actions_twitter from "../integrations/composio/actions/twitter.js";
import type * as integrations_composio_client from "../integrations/composio/client.js";
import type * as integrations_composio_oauth from "../integrations/composio/oauth.js";
import type * as integrations_composio_publishContent from "../integrations/composio/publishContent.js";
import type * as integrations_composio_universalRunner from "../integrations/composio/universalRunner.js";
import type * as integrations_creatify_client from "../integrations/creatify/client.js";
import type * as integrations_creatify_endpoints from "../integrations/creatify/endpoints.js";
import type * as integrations_creatify_types from "../integrations/creatify/types.js";
import type * as integrations_crm_housecallpro from "../integrations/crm/housecallpro.js";
import type * as integrations_crm_index from "../integrations/crm/index.js";
import type * as integrations_crm_jobber from "../integrations/crm/jobber.js";
import type * as integrations_crm_nango from "../integrations/crm/nango.js";
import type * as integrations_crm_nerExtractor from "../integrations/crm/nerExtractor.js";
import type * as integrations_crm_quickbooks from "../integrations/crm/quickbooks.js";
import type * as integrations_dataforseo_client from "../integrations/dataforseo/client.js";
import type * as integrations_gbp_direct_client from "../integrations/gbp/direct/client.js";
import type * as integrations_gbp_index from "../integrations/gbp/index.js";
import type * as integrations_gbp_zernio from "../integrations/gbp/zernio.js";
import type * as integrations_gemini_groundedSearch from "../integrations/gemini/groundedSearch.js";
import type * as integrations_google_calendar from "../integrations/google/calendar.js";
import type * as integrations_google_gmail from "../integrations/google/gmail.js";
import type * as integrations_google_tokenResolver from "../integrations/google/tokenResolver.js";
import type * as integrations_hackerNews_algoliaSearch from "../integrations/hackerNews/algoliaSearch.js";
import type * as integrations_hunter_actions from "../integrations/hunter/actions.js";
import type * as integrations_hunter_client from "../integrations/hunter/client.js";
import type * as integrations_inbox_warmMining from "../integrations/inbox/warmMining.js";
import type * as integrations_inbox_warmMiningAction from "../integrations/inbox/warmMiningAction.js";
import type * as integrations_openclaw_channels from "../integrations/openclaw/channels.js";
import type * as integrations_openclaw_cliClient from "../integrations/openclaw/cliClient.js";
import type * as integrations_photoBridgeWorker_client from "../integrations/photoBridgeWorker/client.js";
import type * as integrations_r2_client from "../integrations/r2/client.js";
import type * as integrations_r2_endpoints from "../integrations/r2/endpoints.js";
import type * as integrations_scrapeCreators___tests___fixtures_instagram from "../integrations/scrapeCreators/__tests__/fixtures/instagram.js";
import type * as integrations_scrapeCreators___tests___fixtures_linkedin from "../integrations/scrapeCreators/__tests__/fixtures/linkedin.js";
import type * as integrations_scrapeCreators___tests___fixtures_tiktok from "../integrations/scrapeCreators/__tests__/fixtures/tiktok.js";
import type * as integrations_scrapeCreators___tests___fixtures_x from "../integrations/scrapeCreators/__tests__/fixtures/x.js";
import type * as integrations_scrapeCreators___tests___fixtures_youtube from "../integrations/scrapeCreators/__tests__/fixtures/youtube.js";
import type * as integrations_scrapeCreators_cache from "../integrations/scrapeCreators/cache.js";
import type * as integrations_scrapeCreators_client from "../integrations/scrapeCreators/client.js";
import type * as integrations_scrapeCreators_endpoints from "../integrations/scrapeCreators/endpoints.js";
import type * as integrations_scrapeCreators_runFullScrapePull from "../integrations/scrapeCreators/runFullScrapePull.js";
import type * as integrations_scrapeCreators_verifyHandle from "../integrations/scrapeCreators/verifyHandle.js";
import type * as integrations_stripe_checkout from "../integrations/stripe/checkout.js";
import type * as integrations_stripe_customerPortal from "../integrations/stripe/customerPortal.js";
import type * as integrations_stripe_priceIds from "../integrations/stripe/priceIds.js";
import type * as integrations_stripe_products from "../integrations/stripe/products.js";
import type * as integrations_stripe_voiceMetering from "../integrations/stripe/voiceMetering.js";
import type * as integrations_stripe_webhooks from "../integrations/stripe/webhooks.js";
import type * as integrations_telegram_client from "../integrations/telegram/client.js";
import type * as integrations_telegram_sendDirectMessage from "../integrations/telegram/sendDirectMessage.js";
import type * as integrations_twilio_client from "../integrations/twilio/client.js";
import type * as integrations_twilio_configureWebhooks from "../integrations/twilio/configureWebhooks.js";
import type * as integrations_twilio_provisionNumber from "../integrations/twilio/provisionNumber.js";
import type * as integrations_twitterApiIo_twitterSearch from "../integrations/twitterApiIo/twitterSearch.js";
import type * as integrations_unipile_client from "../integrations/unipile/client.js";
import type * as integrations_videoSynthWorker_client from "../integrations/videoSynthWorker/client.js";
import type * as integrations_zernio_client from "../integrations/zernio/client.js";
import type * as integrations_zernio_endpoints from "../integrations/zernio/endpoints.js";
import type * as integrations_zernio_oauth from "../integrations/zernio/oauth.js";
import type * as integrations_zernio_types from "../integrations/zernio/types.js";
import type * as integrations_zernio_webhooks from "../integrations/zernio/webhooks.js";
import type * as jobs from "../jobs.js";
import type * as lcMaya_appleCalendarConnect from "../lcMaya/appleCalendarConnect.js";
import type * as lcMaya_calendarHttp from "../lcMaya/calendarHttp.js";
import type * as lcMaya_firstProactivePing from "../lcMaya/firstProactivePing.js";
import type * as lcMaya_gmailHttp from "../lcMaya/gmailHttp.js";
import type * as lcMaya_lcMayaHttp from "../lcMaya/lcMayaHttp.js";
import type * as lcMaya_produceEdit from "../lcMaya/produceEdit.js";
import type * as lcMaya_wikiMirrorSync from "../lcMaya/wikiMirrorSync.js";
import type * as lib_brandOutreachCaps from "../lib/brandOutreachCaps.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_flyClient from "../lib/flyClient.js";
import type * as lib_planFeatures from "../lib/planFeatures.js";
import type * as lib_posthog from "../lib/posthog.js";
import type * as lib_usageEvents from "../lib/usageEvents.js";
import type * as lib_webhookSecret from "../lib/webhookSecret.js";
import type * as mayaActionLog from "../mayaActionLog.js";
import type * as mediaAssets_enqueueCatalog from "../mediaAssets/enqueueCatalog.js";
import type * as mediaAssets_ingest from "../mediaAssets/ingest.js";
import type * as mediaAssets_listAssets from "../mediaAssets/listAssets.js";
import type * as mediaAssets_processCatalogerQueue from "../mediaAssets/processCatalogerQueue.js";
import type * as migrations_coachManagerPlanRename from "../migrations/coachManagerPlanRename.js";
import type * as onboarding_business_deployServiceMaya from "../onboarding/business/deployServiceMaya.js";
import type * as onboarding_business_pipeline from "../onboarding/business/pipeline.js";
import type * as onboarding_growth_deployRiley from "../onboarding/growth/deployRiley.js";
import type * as onboarding_growth_pipeline from "../onboarding/growth/pipeline.js";
import type * as onboarding_gtm_deployMayaGtm from "../onboarding/gtm/deployMayaGtm.js";
import type * as onboarding_maya_deployMaya from "../onboarding/maya/deployMaya.js";
import type * as onboarding_maya_extractEditingFingerprint from "../onboarding/maya/extractEditingFingerprint.js";
import type * as onboarding_maya_jobs from "../onboarding/maya/jobs.js";
import type * as onboarding_maya_submitOnboarding from "../onboarding/maya/submitOnboarding.js";
import type * as onboarding_maya_synthesizeCreatorPicture from "../onboarding/maya/synthesizeCreatorPicture.js";
import type * as onboarding_maya_videoBatching from "../onboarding/maya/videoBatching.js";
import type * as outcomes_attribution from "../outcomes/attribution.js";
import type * as outcomes_gbpInsightsPoller from "../outcomes/gbpInsightsPoller.js";
import type * as outcomes_metaInsightsPoller from "../outcomes/metaInsightsPoller.js";
import type * as outcomes_reviewReplyVerifier from "../outcomes/reviewReplyVerifier.js";
import type * as performance from "../performance.js";
import type * as plan from "../plan.js";
import type * as planService from "../planService.js";
import type * as prePostReview from "../prePostReview.js";
import type * as prePostReviewQueries from "../prePostReviewQueries.js";
import type * as profile from "../profile.js";
import type * as queries_admin_usage from "../queries/admin/usage.js";
import type * as queries_business__session from "../queries/business/_session.js";
import type * as queries_business_customers from "../queries/business/customers.js";
import type * as queries_business_growth from "../queries/business/growth.js";
import type * as queries_business_jobs from "../queries/business/jobs.js";
import type * as queries_business_posts from "../queries/business/posts.js";
import type * as queries_business_profile from "../queries/business/profile.js";
import type * as queries_business_reviews from "../queries/business/reviews.js";
import type * as queries_business_today from "../queries/business/today.js";
import type * as serviceTelemetry from "../serviceTelemetry.js";
import type * as smokeFixtures_cronHeartbeat from "../smokeFixtures/cronHeartbeat.js";
import type * as smokeFixtures_serviceBusiness from "../smokeFixtures/serviceBusiness.js";
import type * as today from "../today.js";
import type * as trends from "../trends.js";
import type * as voice_pinChallenge from "../voice/pinChallenge.js";
import type * as voice_sensitiveOps from "../voice/sensitiveOps.js";
import type * as voice_transcriptHttp from "../voice/transcriptHttp.js";
import type * as voice_transcripts from "../voice/transcripts.js";
import type * as waitlist_mayaProductWaitlist from "../waitlist/mayaProductWaitlist.js";
import type * as webhooks_crm from "../webhooks/crm.js";
import type * as webhooks_qbo from "../webhooks/qbo.js";
import type * as wikiProjections from "../wikiProjections.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_admin/peekState": typeof _admin_peekState;
  "_admin/realWorldDeploy": typeof _admin_realWorldDeploy;
  "_admin/realWorldDeployGtm": typeof _admin_realWorldDeployGtm;
  "_admin/zernioLiveSmoke": typeof _admin_zernioLiveSmoke;
  "_test/serviceFixtures": typeof _test_serviceFixtures;
  accountDeletion: typeof accountDeletion;
  admin: typeof admin;
  "agents/modelRouter/logCall": typeof agents_modelRouter_logCall;
  "agents/modelRouter/maya": typeof agents_modelRouter_maya;
  "agents/modelRouter/openRouterClient": typeof agents_modelRouter_openRouterClient;
  "agents/modelRouter/taskTags": typeof agents_modelRouter_taskTags;
  "agents/packs/maya/configGeneratorMaya": typeof agents_packs_maya_configGeneratorMaya;
  "agents/packs/maya/serializeWorkspaceBundle": typeof agents_packs_maya_serializeWorkspaceBundle;
  "agents/packs/maya/workspace/assembleWorkspaceBundle": typeof agents_packs_maya_workspace_assembleWorkspaceBundle;
  "agents/packs/maya/workspace/buildCronJobsJson": typeof agents_packs_maya_workspace_buildCronJobsJson;
  "agents/packs/maya/workspace/generateAgentsMd": typeof agents_packs_maya_workspace_generateAgentsMd;
  "agents/packs/maya/workspace/generateBootMd": typeof agents_packs_maya_workspace_generateBootMd;
  "agents/packs/maya/workspace/generateDreamingMd": typeof agents_packs_maya_workspace_generateDreamingMd;
  "agents/packs/maya/workspace/generateHeartbeatMd": typeof agents_packs_maya_workspace_generateHeartbeatMd;
  "agents/packs/maya/workspace/generateIdentityMd": typeof agents_packs_maya_workspace_generateIdentityMd;
  "agents/packs/maya/workspace/generateMemoryMdSeed": typeof agents_packs_maya_workspace_generateMemoryMdSeed;
  "agents/packs/maya/workspace/generateSoulMd": typeof agents_packs_maya_workspace_generateSoulMd;
  "agents/packs/maya/workspace/generateToolsMd": typeof agents_packs_maya_workspace_generateToolsMd;
  "agents/packs/maya/workspace/generateUserMd": typeof agents_packs_maya_workspace_generateUserMd;
  "agents/packs/maya/workspace/skillsRegistry": typeof agents_packs_maya_workspace_skillsRegistry;
  "agents/packs/maya/workspace/standingOrders": typeof agents_packs_maya_workspace_standingOrders;
  "agents/packs/maya/workspace/types": typeof agents_packs_maya_workspace_types;
  "agents/packs/maya_gtm/bundledGtmPlugin": typeof agents_packs_maya_gtm_bundledGtmPlugin;
  "agents/packs/maya_gtm/bundledLocalSkills": typeof agents_packs_maya_gtm_bundledLocalSkills;
  "agents/packs/maya_gtm/bundledPlaybook": typeof agents_packs_maya_gtm_bundledPlaybook;
  "agents/packs/maya_gtm/generators": typeof agents_packs_maya_gtm_generators;
  "agents/packs/maya_gtm/pinnedClawhubSkills": typeof agents_packs_maya_gtm_pinnedClawhubSkills;
  "agents/packs/maya_service/anthropicSkillsManifest": typeof agents_packs_maya_service_anthropicSkillsManifest;
  "agents/packs/maya_service/buildJobsJson": typeof agents_packs_maya_service_buildJobsJson;
  "agents/packs/maya_service/clawhubManifest": typeof agents_packs_maya_service_clawhubManifest;
  "agents/packs/maya_service/generateAgents": typeof agents_packs_maya_service_generateAgents;
  "agents/packs/maya_service/generateBoot": typeof agents_packs_maya_service_generateBoot;
  "agents/packs/maya_service/generateBusinessPicture": typeof agents_packs_maya_service_generateBusinessPicture;
  "agents/packs/maya_service/generateDreaming": typeof agents_packs_maya_service_generateDreaming;
  "agents/packs/maya_service/generateHeartbeat": typeof agents_packs_maya_service_generateHeartbeat;
  "agents/packs/maya_service/generateMemorySeed": typeof agents_packs_maya_service_generateMemorySeed;
  "agents/packs/maya_service/generateSoul": typeof agents_packs_maya_service_generateSoul;
  "agents/packs/maya_service/generateTools": typeof agents_packs_maya_service_generateTools;
  "agents/packs/maya_service/memoryWikiConfig": typeof agents_packs_maya_service_memoryWikiConfig;
  "agents/packs/maya_service/runLearningsExtractor": typeof agents_packs_maya_service_runLearningsExtractor;
  "agents/packs/maya_service/standingOrders": typeof agents_packs_maya_service_standingOrders;
  "agents/packs/maya_service/types": typeof agents_packs_maya_service_types;
  "agents/packs/maya_service/voiceCallConfig": typeof agents_packs_maya_service_voiceCallConfig;
  "agents/packs/maya_service/wikiInitialPages": typeof agents_packs_maya_service_wikiInitialPages;
  "agents/packs/riley_growth/clawhubManifest": typeof agents_packs_riley_growth_clawhubManifest;
  "agents/packs/riley_growth/generators": typeof agents_packs_riley_growth_generators;
  "billing/checkout": typeof billing_checkout;
  "billing/gtmBilling": typeof billing_gtmBilling;
  "billing/portal": typeof billing_portal;
  "billing/priceIds": typeof billing_priceIds;
  "billing/stripeClient": typeof billing_stripeClient;
  "billing/webhook": typeof billing_webhook;
  businessReadiness: typeof businessReadiness;
  "creatorMayaV0/backend": typeof creatorMayaV0_backend;
  "creatorMayaV0/brandOutreach": typeof creatorMayaV0_brandOutreach;
  "creatorMayaV0/calendarLookahead": typeof creatorMayaV0_calendarLookahead;
  "creatorMayaV0/calendarScheduling": typeof creatorMayaV0_calendarScheduling;
  "creatorMayaV0/dailyBrief": typeof creatorMayaV0_dailyBrief;
  "creatorMayaV0/editingFingerprintObservations": typeof creatorMayaV0_editingFingerprintObservations;
  "creatorMayaV0/mayaCalendarEvents": typeof creatorMayaV0_mayaCalendarEvents;
  "creatorMayaV0/mediaAssets": typeof creatorMayaV0_mediaAssets;
  "creatorMayaV0/onboardingFlow": typeof creatorMayaV0_onboardingFlow;
  "creatorMayaV0/onboardingIntake": typeof creatorMayaV0_onboardingIntake;
  "creatorMayaV0/openClawDeployGate": typeof creatorMayaV0_openClawDeployGate;
  "creatorMayaV0/openClawMediaIngestHttp": typeof creatorMayaV0_openClawMediaIngestHttp;
  "creatorMayaV0/pinnedClawhubSkills": typeof creatorMayaV0_pinnedClawhubSkills;
  "creatorMayaV0/scope": typeof creatorMayaV0_scope;
  "creatorMayaV0/tiering": typeof creatorMayaV0_tiering;
  "creatorMayaV0/trendBenchmark": typeof creatorMayaV0_trendBenchmark;
  "creatorMayaV0/uploadRenderedMediaHttp": typeof creatorMayaV0_uploadRenderedMediaHttp;
  "creatorMayaV0/videoSampling": typeof creatorMayaV0_videoSampling;
  "creatorMayaV0/workspaceManifest": typeof creatorMayaV0_workspaceManifest;
  creators: typeof creators;
  crons: typeof crons;
  dealTriage: typeof dealTriage;
  deals: typeof deals;
  "founder/dashboard": typeof founder_dashboard;
  "gbp/computeHealthScore": typeof gbp_computeHealthScore;
  "gtmMaya/accountLifecycle": typeof gtmMaya_accountLifecycle;
  "gtmMaya/agentLifecycle": typeof gtmMaya_agentLifecycle;
  "gtmMaya/appInspector": typeof gtmMaya_appInspector;
  "gtmMaya/approvalPublishing": typeof gtmMaya_approvalPublishing;
  "gtmMaya/archetypeBrain": typeof gtmMaya_archetypeBrain;
  "gtmMaya/attribution": typeof gtmMaya_attribution;
  "gtmMaya/autonomyPolicy": typeof gtmMaya_autonomyPolicy;
  "gtmMaya/betaGuards": typeof gtmMaya_betaGuards;
  "gtmMaya/calendarOAuth": typeof gtmMaya_calendarOAuth;
  "gtmMaya/calendarPlan": typeof gtmMaya_calendarPlan;
  "gtmMaya/calendarWrite": typeof gtmMaya_calendarWrite;
  "gtmMaya/channelAgents": typeof gtmMaya_channelAgents;
  "gtmMaya/channelScoring": typeof gtmMaya_channelScoring;
  "gtmMaya/channelSelection": typeof gtmMaya_channelSelection;
  "gtmMaya/channelWarmth": typeof gtmMaya_channelWarmth;
  "gtmMaya/coldStrike": typeof gtmMaya_coldStrike;
  "gtmMaya/contentQuality": typeof gtmMaya_contentQuality;
  "gtmMaya/contentReview": typeof gtmMaya_contentReview;
  "gtmMaya/conversionPing": typeof gtmMaya_conversionPing;
  "gtmMaya/costCap": typeof gtmMaya_costCap;
  "gtmMaya/costLedger": typeof gtmMaya_costLedger;
  "gtmMaya/creatifyVideo": typeof gtmMaya_creatifyVideo;
  "gtmMaya/creativeBudgetGate": typeof gtmMaya_creativeBudgetGate;
  "gtmMaya/dayPlanner": typeof gtmMaya_dayPlanner;
  "gtmMaya/deepLink": typeof gtmMaya_deepLink;
  "gtmMaya/deliveryFailures": typeof gtmMaya_deliveryFailures;
  "gtmMaya/demandIntel": typeof gtmMaya_demandIntel;
  "gtmMaya/discoveryBudgetGate": typeof gtmMaya_discoveryBudgetGate;
  "gtmMaya/distributionMotions": typeof gtmMaya_distributionMotions;
  "gtmMaya/engagementLedger": typeof gtmMaya_engagementLedger;
  "gtmMaya/evidenceGuard": typeof gtmMaya_evidenceGuard;
  "gtmMaya/experimentPlanner": typeof gtmMaya_experimentPlanner;
  "gtmMaya/experimentStats": typeof gtmMaya_experimentStats;
  "gtmMaya/experiments": typeof gtmMaya_experiments;
  "gtmMaya/formatIntel": typeof gtmMaya_formatIntel;
  "gtmMaya/intentStrike": typeof gtmMaya_intentStrike;
  "gtmMaya/judgeCardsBatch": typeof gtmMaya_judgeCardsBatch;
  "gtmMaya/judgeChannel": typeof gtmMaya_judgeChannel;
  "gtmMaya/livenessWatch": typeof gtmMaya_livenessWatch;
  "gtmMaya/managerStore": typeof gtmMaya_managerStore;
  "gtmMaya/mediaAssets": typeof gtmMaya_mediaAssets;
  "gtmMaya/memoryLedger": typeof gtmMaya_memoryLedger;
  "gtmMaya/mineCommentTrees": typeof gtmMaya_mineCommentTrees;
  "gtmMaya/missionBoard": typeof gtmMaya_missionBoard;
  "gtmMaya/missionControl": typeof gtmMaya_missionControl;
  "gtmMaya/openclaw/conversationCapture": typeof gtmMaya_openclaw_conversationCapture;
  "gtmMaya/openclaw/hookClient": typeof gtmMaya_openclaw_hookClient;
  "gtmMaya/openclaw/inboundCallback": typeof gtmMaya_openclaw_inboundCallback;
  "gtmMaya/openclaw/llmGateway": typeof gtmMaya_openclaw_llmGateway;
  "gtmMaya/openclaw/managerCallbacks": typeof gtmMaya_openclaw_managerCallbacks;
  "gtmMaya/openclaw/planCallbacks": typeof gtmMaya_openclaw_planCallbacks;
  "gtmMaya/openclaw/pulseCallbacks": typeof gtmMaya_openclaw_pulseCallbacks;
  "gtmMaya/openclaw/traceCapture": typeof gtmMaya_openclaw_traceCapture;
  "gtmMaya/openrouterSpend": typeof gtmMaya_openrouterSpend;
  "gtmMaya/outboundFirewall": typeof gtmMaya_outboundFirewall;
  "gtmMaya/phase2Trigger": typeof gtmMaya_phase2Trigger;
  "gtmMaya/planGtm": typeof gtmMaya_planGtm;
  "gtmMaya/platformAlgo": typeof gtmMaya_platformAlgo;
  "gtmMaya/platformIntelligence": typeof gtmMaya_platformIntelligence;
  "gtmMaya/platformWorkers": typeof gtmMaya_platformWorkers;
  "gtmMaya/postResults": typeof gtmMaya_postResults;
  "gtmMaya/privateBeta": typeof gtmMaya_privateBeta;
  "gtmMaya/productPicture": typeof gtmMaya_productPicture;
  "gtmMaya/productionReadiness": typeof gtmMaya_productionReadiness;
  "gtmMaya/productionReality": typeof gtmMaya_productionReality;
  "gtmMaya/providerPricing": typeof gtmMaya_providerPricing;
  "gtmMaya/publishEngine": typeof gtmMaya_publishEngine;
  "gtmMaya/publishWorkflow": typeof gtmMaya_publishWorkflow;
  "gtmMaya/queryExpansion": typeof gtmMaya_queryExpansion;
  "gtmMaya/recordPublished": typeof gtmMaya_recordPublished;
  "gtmMaya/researchLifecycle": typeof gtmMaya_researchLifecycle;
  "gtmMaya/researchQueryBuilder": typeof gtmMaya_researchQueryBuilder;
  "gtmMaya/researchQueryRunner": typeof gtmMaya_researchQueryRunner;
  "gtmMaya/researchResults": typeof gtmMaya_researchResults;
  "gtmMaya/researchTasks": typeof gtmMaya_researchTasks;
  "gtmMaya/researchWorker": typeof gtmMaya_researchWorker;
  "gtmMaya/resultsLoop": typeof gtmMaya_resultsLoop;
  "gtmMaya/scrapeCreatorsGtmResearch": typeof gtmMaya_scrapeCreatorsGtmResearch;
  "gtmMaya/spendKill": typeof gtmMaya_spendKill;
  "gtmMaya/steering": typeof gtmMaya_steering;
  "gtmMaya/strategicDiagnosis": typeof gtmMaya_strategicDiagnosis;
  "gtmMaya/strategyJudge": typeof gtmMaya_strategyJudge;
  "gtmMaya/synthesisDelivery": typeof gtmMaya_synthesisDelivery;
  "gtmMaya/targetList": typeof gtmMaya_targetList;
  "gtmMaya/telegramBotPerTenant": typeof gtmMaya_telegramBotPerTenant;
  "gtmMaya/telegramConfirm": typeof gtmMaya_telegramConfirm;
  "gtmMaya/telegramHandoff": typeof gtmMaya_telegramHandoff;
  "gtmMaya/telegramPairing": typeof gtmMaya_telegramPairing;
  "gtmMaya/telegramWebhook": typeof gtmMaya_telegramWebhook;
  "gtmMaya/tiktokWarmup": typeof gtmMaya_tiktokWarmup;
  "gtmMaya/voiceProfile": typeof gtmMaya_voiceProfile;
  "gtmMaya/walkthrough": typeof gtmMaya_walkthrough;
  "gtmMaya/watermarks": typeof gtmMaya_watermarks;
  "gtmMaya/webSearch": typeof gtmMaya_webSearch;
  "gtmMaya/workspaceMutator": typeof gtmMaya_workspaceMutator;
  "gtmMaya/zernioConnect": typeof gtmMaya_zernioConnect;
  "gtmMaya/zernioReads": typeof gtmMaya_zernioReads;
  "gtmMaya/zernioRoutes": typeof gtmMaya_zernioRoutes;
  "gtmMaya/zernioWebhook": typeof gtmMaya_zernioWebhook;
  http: typeof http;
  "integrations/aggregators/unified/client": typeof integrations_aggregators_unified_client;
  "integrations/aggregators/unified/types": typeof integrations_aggregators_unified_types;
  "integrations/apify/twitterScraper": typeof integrations_apify_twitterScraper;
  "integrations/apollo/actions": typeof integrations_apollo_actions;
  "integrations/apollo/client": typeof integrations_apollo_client;
  "integrations/appStore/playScraper": typeof integrations_appStore_playScraper;
  "integrations/appStore/storeListing": typeof integrations_appStore_storeListing;
  "integrations/apple/caldav": typeof integrations_apple_caldav;
  "integrations/composio/actions/calendar": typeof integrations_composio_actions_calendar;
  "integrations/composio/actions/gmail": typeof integrations_composio_actions_gmail;
  "integrations/composio/actions/index": typeof integrations_composio_actions_index;
  "integrations/composio/actions/linkedin": typeof integrations_composio_actions_linkedin;
  "integrations/composio/actions/stripe": typeof integrations_composio_actions_stripe;
  "integrations/composio/actions/twitter": typeof integrations_composio_actions_twitter;
  "integrations/composio/client": typeof integrations_composio_client;
  "integrations/composio/oauth": typeof integrations_composio_oauth;
  "integrations/composio/publishContent": typeof integrations_composio_publishContent;
  "integrations/composio/universalRunner": typeof integrations_composio_universalRunner;
  "integrations/creatify/client": typeof integrations_creatify_client;
  "integrations/creatify/endpoints": typeof integrations_creatify_endpoints;
  "integrations/creatify/types": typeof integrations_creatify_types;
  "integrations/crm/housecallpro": typeof integrations_crm_housecallpro;
  "integrations/crm/index": typeof integrations_crm_index;
  "integrations/crm/jobber": typeof integrations_crm_jobber;
  "integrations/crm/nango": typeof integrations_crm_nango;
  "integrations/crm/nerExtractor": typeof integrations_crm_nerExtractor;
  "integrations/crm/quickbooks": typeof integrations_crm_quickbooks;
  "integrations/dataforseo/client": typeof integrations_dataforseo_client;
  "integrations/gbp/direct/client": typeof integrations_gbp_direct_client;
  "integrations/gbp/index": typeof integrations_gbp_index;
  "integrations/gbp/zernio": typeof integrations_gbp_zernio;
  "integrations/gemini/groundedSearch": typeof integrations_gemini_groundedSearch;
  "integrations/google/calendar": typeof integrations_google_calendar;
  "integrations/google/gmail": typeof integrations_google_gmail;
  "integrations/google/tokenResolver": typeof integrations_google_tokenResolver;
  "integrations/hackerNews/algoliaSearch": typeof integrations_hackerNews_algoliaSearch;
  "integrations/hunter/actions": typeof integrations_hunter_actions;
  "integrations/hunter/client": typeof integrations_hunter_client;
  "integrations/inbox/warmMining": typeof integrations_inbox_warmMining;
  "integrations/inbox/warmMiningAction": typeof integrations_inbox_warmMiningAction;
  "integrations/openclaw/channels": typeof integrations_openclaw_channels;
  "integrations/openclaw/cliClient": typeof integrations_openclaw_cliClient;
  "integrations/photoBridgeWorker/client": typeof integrations_photoBridgeWorker_client;
  "integrations/r2/client": typeof integrations_r2_client;
  "integrations/r2/endpoints": typeof integrations_r2_endpoints;
  "integrations/scrapeCreators/__tests__/fixtures/instagram": typeof integrations_scrapeCreators___tests___fixtures_instagram;
  "integrations/scrapeCreators/__tests__/fixtures/linkedin": typeof integrations_scrapeCreators___tests___fixtures_linkedin;
  "integrations/scrapeCreators/__tests__/fixtures/tiktok": typeof integrations_scrapeCreators___tests___fixtures_tiktok;
  "integrations/scrapeCreators/__tests__/fixtures/x": typeof integrations_scrapeCreators___tests___fixtures_x;
  "integrations/scrapeCreators/__tests__/fixtures/youtube": typeof integrations_scrapeCreators___tests___fixtures_youtube;
  "integrations/scrapeCreators/cache": typeof integrations_scrapeCreators_cache;
  "integrations/scrapeCreators/client": typeof integrations_scrapeCreators_client;
  "integrations/scrapeCreators/endpoints": typeof integrations_scrapeCreators_endpoints;
  "integrations/scrapeCreators/runFullScrapePull": typeof integrations_scrapeCreators_runFullScrapePull;
  "integrations/scrapeCreators/verifyHandle": typeof integrations_scrapeCreators_verifyHandle;
  "integrations/stripe/checkout": typeof integrations_stripe_checkout;
  "integrations/stripe/customerPortal": typeof integrations_stripe_customerPortal;
  "integrations/stripe/priceIds": typeof integrations_stripe_priceIds;
  "integrations/stripe/products": typeof integrations_stripe_products;
  "integrations/stripe/voiceMetering": typeof integrations_stripe_voiceMetering;
  "integrations/stripe/webhooks": typeof integrations_stripe_webhooks;
  "integrations/telegram/client": typeof integrations_telegram_client;
  "integrations/telegram/sendDirectMessage": typeof integrations_telegram_sendDirectMessage;
  "integrations/twilio/client": typeof integrations_twilio_client;
  "integrations/twilio/configureWebhooks": typeof integrations_twilio_configureWebhooks;
  "integrations/twilio/provisionNumber": typeof integrations_twilio_provisionNumber;
  "integrations/twitterApiIo/twitterSearch": typeof integrations_twitterApiIo_twitterSearch;
  "integrations/unipile/client": typeof integrations_unipile_client;
  "integrations/videoSynthWorker/client": typeof integrations_videoSynthWorker_client;
  "integrations/zernio/client": typeof integrations_zernio_client;
  "integrations/zernio/endpoints": typeof integrations_zernio_endpoints;
  "integrations/zernio/oauth": typeof integrations_zernio_oauth;
  "integrations/zernio/types": typeof integrations_zernio_types;
  "integrations/zernio/webhooks": typeof integrations_zernio_webhooks;
  jobs: typeof jobs;
  "lcMaya/appleCalendarConnect": typeof lcMaya_appleCalendarConnect;
  "lcMaya/calendarHttp": typeof lcMaya_calendarHttp;
  "lcMaya/firstProactivePing": typeof lcMaya_firstProactivePing;
  "lcMaya/gmailHttp": typeof lcMaya_gmailHttp;
  "lcMaya/lcMayaHttp": typeof lcMaya_lcMayaHttp;
  "lcMaya/produceEdit": typeof lcMaya_produceEdit;
  "lcMaya/wikiMirrorSync": typeof lcMaya_wikiMirrorSync;
  "lib/brandOutreachCaps": typeof lib_brandOutreachCaps;
  "lib/encryption": typeof lib_encryption;
  "lib/flyClient": typeof lib_flyClient;
  "lib/planFeatures": typeof lib_planFeatures;
  "lib/posthog": typeof lib_posthog;
  "lib/usageEvents": typeof lib_usageEvents;
  "lib/webhookSecret": typeof lib_webhookSecret;
  mayaActionLog: typeof mayaActionLog;
  "mediaAssets/enqueueCatalog": typeof mediaAssets_enqueueCatalog;
  "mediaAssets/ingest": typeof mediaAssets_ingest;
  "mediaAssets/listAssets": typeof mediaAssets_listAssets;
  "mediaAssets/processCatalogerQueue": typeof mediaAssets_processCatalogerQueue;
  "migrations/coachManagerPlanRename": typeof migrations_coachManagerPlanRename;
  "onboarding/business/deployServiceMaya": typeof onboarding_business_deployServiceMaya;
  "onboarding/business/pipeline": typeof onboarding_business_pipeline;
  "onboarding/growth/deployRiley": typeof onboarding_growth_deployRiley;
  "onboarding/growth/pipeline": typeof onboarding_growth_pipeline;
  "onboarding/gtm/deployMayaGtm": typeof onboarding_gtm_deployMayaGtm;
  "onboarding/maya/deployMaya": typeof onboarding_maya_deployMaya;
  "onboarding/maya/extractEditingFingerprint": typeof onboarding_maya_extractEditingFingerprint;
  "onboarding/maya/jobs": typeof onboarding_maya_jobs;
  "onboarding/maya/submitOnboarding": typeof onboarding_maya_submitOnboarding;
  "onboarding/maya/synthesizeCreatorPicture": typeof onboarding_maya_synthesizeCreatorPicture;
  "onboarding/maya/videoBatching": typeof onboarding_maya_videoBatching;
  "outcomes/attribution": typeof outcomes_attribution;
  "outcomes/gbpInsightsPoller": typeof outcomes_gbpInsightsPoller;
  "outcomes/metaInsightsPoller": typeof outcomes_metaInsightsPoller;
  "outcomes/reviewReplyVerifier": typeof outcomes_reviewReplyVerifier;
  performance: typeof performance;
  plan: typeof plan;
  planService: typeof planService;
  prePostReview: typeof prePostReview;
  prePostReviewQueries: typeof prePostReviewQueries;
  profile: typeof profile;
  "queries/admin/usage": typeof queries_admin_usage;
  "queries/business/_session": typeof queries_business__session;
  "queries/business/customers": typeof queries_business_customers;
  "queries/business/growth": typeof queries_business_growth;
  "queries/business/jobs": typeof queries_business_jobs;
  "queries/business/posts": typeof queries_business_posts;
  "queries/business/profile": typeof queries_business_profile;
  "queries/business/reviews": typeof queries_business_reviews;
  "queries/business/today": typeof queries_business_today;
  serviceTelemetry: typeof serviceTelemetry;
  "smokeFixtures/cronHeartbeat": typeof smokeFixtures_cronHeartbeat;
  "smokeFixtures/serviceBusiness": typeof smokeFixtures_serviceBusiness;
  today: typeof today;
  trends: typeof trends;
  "voice/pinChallenge": typeof voice_pinChallenge;
  "voice/sensitiveOps": typeof voice_sensitiveOps;
  "voice/transcriptHttp": typeof voice_transcriptHttp;
  "voice/transcripts": typeof voice_transcripts;
  "waitlist/mayaProductWaitlist": typeof waitlist_mayaProductWaitlist;
  "webhooks/crm": typeof webhooks_crm;
  "webhooks/qbo": typeof webhooks_qbo;
  wikiProjections: typeof wikiProjections;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
